/****************************************Copyright (c)************************************************
** File name:			external_flash.h
** Last modified Date:          
** Last Version:		V1.0   
** Created by:			谢彪
** Created date:		2020-06-30
** Version:			    1.0
** Descriptions:		外挂flash驱动头文件
******************************************************************************************************/
#ifndef __EXTERNAL_FLASH_H__
#define __EXTERNAL_FLASH_H__

#include <stdint.h>

//SPI引脚定义
#define FLASH_DEVICE 	"SPI_2"
#define FLASH_NAME 		"W25Q64FW"
#define FLASH_PORT		"GPIO_0"
#define FLASH_CS_PIN		(2)
#define FLASH_CLK_PIN		(3)
#define FLASH_MOSI_PIN		(4)
#define FLASH_MISO_PIN		(5)

//W25Q64 ID
#define	W25Q64_ID	0XEF16

//SPI Flash命令定义
#define	SPIFlash_WriteEnable	0x06  //写使能命令
#define	SPIFlash_WriteDisable	0x04  //写禁止命令
#define	SPIFlash_PageProgram	0x02  //页写入命令
#define	SPIFlash_ReadStatusReg	0x05  //读状态寄存器1
#define	SPIFlash_WriteStatusReg	0x01  //写状态寄存器1
#define	SPIFlash_ReadData		0x03  //读数据命令
#define	SPIFlash_SecErase		0x20  //扇区擦除
#define	SPIFlash_BlockErase		0xD8  //块擦除
#define	SPIFlash_ChipErase		0xC7  //全片擦除
#define	SPIFlash_ReadID			0x90  //读取ID

#define	SPIFLASH_CMD_LENGTH		0x04
#define	SPIFLASH_WRITE_BUSYBIT	0x01

#define	SPIFlash_PAGE_SIZE		256
#define SPIFlash_PAGE_NUMBER	32768

#define	SPIFlash_SECTOR_SIZE	4096
#define SPIFlash_SECTOR_NUMBER	2048

#define	SPI_TXRX_MAX_LEN		(1024*4)	//255	(1024*2)

#define SPIFlash_BLOCK_SIZE		64
#define	SPIFlash_BLOCK_NUMBLE	128

//IMG在flash里占用4M的空间(0x000000~0x3FFFFF)
#define IMG_START_ADDR			0x000000
#define IMG_OFFSET				0
//analog clock
#define IMG_ANALOG_CLOCK_BG_ADDR			IMG_START_ADDR
#define IMG_ANALOG_CLOCK_BG_SIZE			(115208)
#define IMG_ANALOG_CLOCK_BG_END				(IMG_ANALOG_CLOCK_BG_ADDR+IMG_ANALOG_CLOCK_BG_SIZE)
#define IMG_ANALOG_CLOCK_DOT_WHITE_ADDR		(IMG_ANALOG_CLOCK_BG_END+IMG_OFFSET)
#define IMG_ANALOG_CLOCK_DOT_WHITE_SIZE		(458)
#define IMG_ANALOG_CLOCK_DOT_WHITE_END		(IMG_ANALOG_CLOCK_DOT_WHITE_ADDR+IMG_ANALOG_CLOCK_DOT_WHITE_SIZE)
#define IMG_ANALOG_CLOCK_DOT_RED_ADDR		(IMG_ANALOG_CLOCK_DOT_WHITE_END+IMG_OFFSET)
#define IMG_ANALOG_CLOCK_DOT_RED_SIZE		(250)
#define IMG_ANALOG_CLOCK_DOT_RED_END		(IMG_ANALOG_CLOCK_DOT_RED_ADDR+IMG_ANALOG_CLOCK_DOT_RED_SIZE)
#define IMG_ANALOG_CLOCK_HAND_SEC_ADDR		(IMG_ANALOG_CLOCK_DOT_RED_END+IMG_OFFSET)
#define IMG_ANALOG_CLOCK_HAND_SEC_SIZE		(332)
#define IMG_ANALOG_CLOCK_HAND_SEC_END		(IMG_ANALOG_CLOCK_HAND_SEC_ADDR+IMG_ANALOG_CLOCK_HAND_SEC_SIZE)
#define IMG_ANALOG_CLOCK_HAND_MIN_ADDR		(IMG_ANALOG_CLOCK_HAND_SEC_END+IMG_OFFSET)
#define IMG_ANALOG_CLOCK_HAND_MIN_SIZE		(1268)
#define IMG_ANALOG_CLOCK_HAND_MIN_END		(IMG_ANALOG_CLOCK_HAND_MIN_ADDR+IMG_ANALOG_CLOCK_HAND_MIN_SIZE)
#define IMG_ANALOG_CLOCK_HAND_HOUR_ADDR		(IMG_ANALOG_CLOCK_HAND_MIN_END+IMG_OFFSET)
#define IMG_ANALOG_CLOCK_HAND_HOUR_SIZE		(962)
#define IMG_ANALOG_CLOCK_HAND_HOUR_END		(IMG_ANALOG_CLOCK_HAND_HOUR_ADDR+IMG_ANALOG_CLOCK_HAND_HOUR_SIZE)
//battery
#define IMG_BAT_RECT_RED_ADDR				(IMG_ANALOG_CLOCK_HAND_HOUR_END+IMG_OFFSET)
#define IMG_BAT_RECT_RED_SIZE				(968)
#define IMG_BAT_RECT_RED_END				(IMG_BAT_RECT_RED_ADDR+IMG_BAT_RECT_RED_SIZE)
#define IMG_BAT_RECT_WHITE_ADDR				(IMG_BAT_RECT_RED_END+IMG_OFFSET)
#define IMG_BAT_RECT_WHITE_SIZE				(968)
#define IMG_BAT_RECT_WHITE_END				(IMG_BAT_RECT_WHITE_ADDR+IMG_BAT_RECT_WHITE_SIZE)
//blood pressure
#define IMG_BP_BG_ADDR						(IMG_BAT_RECT_WHITE_END+IMG_OFFSET)
#define IMG_BP_BG_SIZE						(35368)
#define IMG_BP_BG_END						(IMG_BP_BG_ADDR+IMG_BP_BG_SIZE)
#define IMG_BP_DOWN_ARRAW_ADDR				(IMG_BP_BG_END+IMG_OFFSET)
#define IMG_BP_DOWN_ARRAW_SIZE				(392)
#define	IMG_BP_DOWN_ARRAW_END				(IMG_BP_DOWN_ARRAW_ADDR+IMG_BP_DOWN_ARRAW_SIZE)
#define	IMG_BP_ICON_ANI_1_ADDR				(IMG_BP_DOWN_ARRAW_END+IMG_OFFSET)
#define IMG_BP_ICON_ANI_1_SIZE				(1768)
#define IMG_BP_ICON_ANI_1_END				(IMG_BP_ICON_ANI_1_ADDR+IMG_BP_ICON_ANI_1_SIZE)
#define IMG_BP_ICON_ANI_2_ADDR				(IMG_BP_ICON_ANI_1_END+IMG_OFFSET)
#define IMG_BP_ICON_ANI_2_SIZE				(1768)
#define IMG_BP_ICON_ANI_2_END				(IMG_BP_ICON_ANI_2_ADDR+IMG_BP_ICON_ANI_2_SIZE)
#define IMG_BP_ICON_ANI_3_ADDR				(IMG_BP_ICON_ANI_2_END+IMG_OFFSET)
#define IMG_BP_ICON_ANI_3_SIZE				(1768)
#define IMG_BP_ICON_ANI_3_END				(IMG_BP_ICON_ANI_3_ADDR+IMG_BP_ICON_ANI_3_SIZE)
#define IMG_BP_MMHG_ADDR					(IMG_BP_ICON_ANI_3_END+IMG_OFFSET)
#define IMG_BP_MMHG_SIZE					(1044)
#define IMG_BP_MMHG_END						(IMG_BP_MMHG_ADDR+IMG_BP_MMHG_SIZE)
#define IMG_BP_SPE_LINE_ADDR				(IMG_BP_MMHG_END+IMG_OFFSET)
#define IMG_BP_SPE_LINE_SIZE				(504)
#define IMG_BP_SPE_LINE_END					(IMG_BP_SPE_LINE_ADDR+IMG_BP_SPE_LINE_SIZE)
#define IMG_BP_TIME_DOT_ADDR				(IMG_BP_SPE_LINE_END+IMG_OFFSET)
#define IMG_BP_TIME_DOT_SIZE				(28)
#define IMG_BP_TIME_DOT_END					(IMG_BP_TIME_DOT_ADDR+IMG_BP_TIME_DOT_SIZE)
#define IMG_BP_UP_ARRAW_ADDR				(IMG_BP_TIME_DOT_END+IMG_OFFSET)
#define IMG_BP_UP_ARRAW_SIZE				(586)
#define IMG_BP_UP_ARRAW_END					(IMG_BP_UP_ARRAW_ADDR+IMG_BP_UP_ARRAW_SIZE)
//heart rate
#define IMG_HR_BG_ADDR						(IMG_BP_UP_ARRAW_END+IMG_OFFSET)
#define IMG_HR_BG_SIZE						(35440)
#define IMG_HR_BG_END						(IMG_HR_BG_ADDR+IMG_HR_BG_SIZE)
#define IMG_HR_BPM_ADDR						(IMG_HR_BG_END+IMG_OFFSET)
#define IMG_HR_BPM_SIZE						(1988)
#define IMG_HR_BPM_END						(IMG_HR_BPM_ADDR+IMG_HR_BPM_SIZE)
#define IMG_HR_DOWN_ARRAW_ADDR				(IMG_HR_BPM_END+IMG_OFFSET)
#define IMG_HR_DOWN_ARRAW_SIZE				(548)
#define IMG_HR_DOWN_ARRAW_END				(IMG_HR_DOWN_ARRAW_ADDR+IMG_HR_DOWN_ARRAW_SIZE)
#define	IMG_HR_ICON_ANI_1_ADDR				(IMG_HR_DOWN_ARRAW_END+IMG_OFFSET)
#define	IMG_HR_ICON_ANI_1_SIZE				(2116)
#define	IMG_HR_ICON_ANI_1_END				(IMG_HR_ICON_ANI_1_ADDR+IMG_HR_ICON_ANI_1_SIZE)
#define	IMG_HR_ICON_ANI_2_ADDR				(IMG_HR_ICON_ANI_1_END+IMG_OFFSET)
#define	IMG_HR_ICON_ANI_2_SIZE				(2116)
#define	IMG_HR_ICON_ANI_2_END				(IMG_HR_ICON_ANI_2_ADDR+IMG_HR_ICON_ANI_2_SIZE)
#define IMG_HR_TIME_DOT_ADDR				(IMG_HR_ICON_ANI_2_END+IMG_OFFSET)
#define IMG_HR_TIME_DOT_SIZE				(28)
#define IMG_HR_TIME_DOT_END					(IMG_HR_TIME_DOT_ADDR+IMG_HR_TIME_DOT_SIZE)
#define IMG_HR_UP_ARRAW_ADDR				(IMG_HR_TIME_DOT_END+IMG_OFFSET)
#define IMG_HR_UP_ARRAW_SIZE				(484)
#define IMG_HR_UP_ARRAW_END					(IMG_HR_UP_ARRAW_ADDR+IMG_HR_UP_ARRAW_SIZE)
//idle step
#define IMG_IDLE_STEP_LOGO_ADDR				(IMG_HR_UP_ARRAW_END+IMG_OFFSET)
#define	IMG_IDLE_STEP_LOGO_SIZE				(20072)
#define IMG_IDLE_STEP_LOGO_END				(IMG_IDLE_STEP_LOGO_ADDR+IMG_IDLE_STEP_LOGO_SIZE)
#define IMG_IDLE_STEP_NUM_0_ADDR			(IMG_IDLE_STEP_LOGO_END+IMG_OFFSET)
#define IMG_IDLE_STEP_NUM_0_SIZE			(1304)
#define IMG_IDLE_STEP_NUM_0_END				(IMG_IDLE_STEP_NUM_0_ADDR+IMG_IDLE_STEP_NUM_0_SIZE)
#define IMG_IDLE_STEP_NUM_1_ADDR			(IMG_IDLE_STEP_NUM_0_END+IMG_OFFSET)
#define IMG_IDLE_STEP_NUM_1_SIZE			(1304)
#define IMG_IDLE_STEP_NUM_1_END				(IMG_IDLE_STEP_NUM_1_ADDR+IMG_IDLE_STEP_NUM_1_SIZE)
#define IMG_IDLE_STEP_NUM_2_ADDR			(IMG_IDLE_STEP_NUM_1_END+IMG_OFFSET)
#define IMG_IDLE_STEP_NUM_2_SIZE			(1304)
#define IMG_IDLE_STEP_NUM_2_END				(IMG_IDLE_STEP_NUM_2_ADDR+IMG_IDLE_STEP_NUM_2_SIZE)
#define IMG_IDLE_STEP_NUM_3_ADDR			(IMG_IDLE_STEP_NUM_2_END+IMG_OFFSET)
#define IMG_IDLE_STEP_NUM_3_SIZE			(1304)
#define IMG_IDLE_STEP_NUM_3_END				(IMG_IDLE_STEP_NUM_3_ADDR+IMG_IDLE_STEP_NUM_3_SIZE)
#define IMG_IDLE_STEP_NUM_4_ADDR			(IMG_IDLE_STEP_NUM_3_END+IMG_OFFSET)
#define IMG_IDLE_STEP_NUM_4_SIZE			(1304)
#define IMG_IDLE_STEP_NUM_4_END				(IMG_IDLE_STEP_NUM_4_ADDR+IMG_IDLE_STEP_NUM_4_SIZE)
#define IMG_IDLE_STEP_NUM_5_ADDR			(IMG_IDLE_STEP_NUM_4_END+IMG_OFFSET)
#define IMG_IDLE_STEP_NUM_5_SIZE			(1304)
#define IMG_IDLE_STEP_NUM_5_END				(IMG_IDLE_STEP_NUM_5_ADDR+IMG_IDLE_STEP_NUM_5_SIZE)
#define IMG_IDLE_STEP_NUM_6_ADDR			(IMG_IDLE_STEP_NUM_5_END+IMG_OFFSET)
#define IMG_IDLE_STEP_NUM_6_SIZE			(1304)
#define IMG_IDLE_STEP_NUM_6_END				(IMG_IDLE_STEP_NUM_6_ADDR+IMG_IDLE_STEP_NUM_6_SIZE)
#define IMG_IDLE_STEP_NUM_7_ADDR			(IMG_IDLE_STEP_NUM_6_END+IMG_OFFSET)
#define IMG_IDLE_STEP_NUM_7_SIZE			(1304)
#define IMG_IDLE_STEP_NUM_7_END				(IMG_IDLE_STEP_NUM_7_ADDR+IMG_IDLE_STEP_NUM_7_SIZE)
#define IMG_IDLE_STEP_NUM_8_ADDR			(IMG_IDLE_STEP_NUM_7_END+IMG_OFFSET)
#define IMG_IDLE_STEP_NUM_8_SIZE			(1304)
#define IMG_IDLE_STEP_NUM_8_END				(IMG_IDLE_STEP_NUM_8_ADDR+IMG_IDLE_STEP_NUM_8_SIZE)
#define IMG_IDLE_STEP_NUM_9_ADDR			(IMG_IDLE_STEP_NUM_8_END+IMG_OFFSET)
#define IMG_IDLE_STEP_NUM_9_SIZE			(1304)
#define IMG_IDLE_STEP_NUM_9_END				(IMG_IDLE_STEP_NUM_9_ADDR+IMG_IDLE_STEP_NUM_9_SIZE)
//ota
#define IMG_OTA_DOWNLOADING_ADDR			(IMG_IDLE_STEP_NUM_9_END+IMG_OFFSET)
#define IMG_OTA_DOWNLOADING_SIZE			(7460)
#define IMG_OTA_DOWNLOADING_END				(IMG_OTA_DOWNLOADING_ADDR+IMG_OTA_DOWNLOADING_SIZE)
#define	IMG_OTA_FAILED_ICON_ADDR			(IMG_OTA_DOWNLOADING_END+IMG_OFFSET)
#define IMG_OTA_FAILED_ICON_SIZE			(21640)
#define IMG_OTA_FAILED_ICON_END				(IMG_OTA_FAILED_ICON_ADDR+IMG_OTA_FAILED_ICON_SIZE)
#define IMG_OTA_FINISH_ADDR					(IMG_OTA_FAILED_ICON_END+IMG_OFFSET)
#define IMG_OTA_FINISH_SIZE					(115208)
#define IMG_OTA_FINISH_END					(IMG_OTA_FINISH_ADDR+IMG_OTA_FINISH_SIZE)
#define	IMG_OTA_LOGO_ADDR					(IMG_OTA_FINISH_END+IMG_OFFSET)
#define IMG_OTA_LOGO_SIZE					(7208)
#define IMG_OTA_LOGO_END					(IMG_OTA_LOGO_ADDR+IMG_OTA_LOGO_SIZE)
#define	IMG_OTA_NO_ADDR						(IMG_OTA_LOGO_END+IMG_OFFSET)
#define IMG_OTA_NO_SIZE						(3208)
#define IMG_OTA_NO_END						(IMG_OTA_NO_ADDR+IMG_OTA_NO_SIZE)
#define IMG_OTA_RUNNING_FAIL_ADDR			(IMG_OTA_NO_END+IMG_OFFSET)
#define IMG_OTA_RUNNING_FAIL_SIZE			(3572)
#define IMG_OTA_RUNNING_FAIL_END			(IMG_OTA_RUNNING_FAIL_ADDR+IMG_OTA_RUNNING_FAIL_SIZE)
#define IMG_OTA_RUNNING_STR_ADDR			(IMG_OTA_RUNNING_FAIL_END+IMG_OFFSET)
#define IMG_OTA_RUNNING_STR_SIZE			(5516)
#define IMG_OTA_RUNNING_STR_END				(IMG_OTA_RUNNING_STR_ADDR+IMG_OTA_RUNNING_STR_SIZE)
#define IMG_OTA_STR_ADDR					(IMG_OTA_RUNNING_STR_END+IMG_OFFSET)
#define IMG_OTA_STR_SIZE					(19748)
#define IMG_OTA_STR_END						(IMG_OTA_STR_ADDR+IMG_OTA_STR_SIZE)
#define IMG_OTA_YES_ADDR					(IMG_OTA_STR_END+IMG_OFFSET)
#define IMG_OTA_YES_SIZE					(3208)
#define IMG_OTA_YES_END						(IMG_OTA_YES_ADDR+IMG_OTA_YES_SIZE)
//power off
#define IMG_PWROFF_ANI_1_ADDR				(IMG_OTA_YES_END+IMG_OFFSET)
#define IMG_PWROFF_ANI_1_SIZE				(29776)
#define IMG_PWROFF_ANI_1_END				(IMG_PWROFF_ANI_1_ADDR+IMG_PWROFF_ANI_1_SIZE)
#define IMG_PWROFF_ANI_2_ADDR				(IMG_PWROFF_ANI_1_END+IMG_OFFSET)
#define IMG_PWROFF_ANI_2_SIZE				(29776)
#define IMG_PWROFF_ANI_2_END				(IMG_PWROFF_ANI_2_ADDR+IMG_PWROFF_ANI_2_SIZE)
#define	IMG_PWROFF_ANI_3_ADDR				(IMG_PWROFF_ANI_2_END+IMG_OFFSET)
#define IMG_PWROFF_ANI_3_SIZE				(29776)
#define IMG_PWROFF_ANI_3_END				(IMG_PWROFF_ANI_3_ADDR+IMG_PWROFF_ANI_3_SIZE)
#define IMG_PWROFF_ANI_4_ADDR				(IMG_PWROFF_ANI_3_END+IMG_OFFSET)
#define IMG_PWROFF_ANI_4_SIZE				(29776)
#define IMG_PWROFF_ANI_4_END				(IMG_PWROFF_ANI_4_ADDR+IMG_PWROFF_ANI_4_SIZE)
#define IMG_PWROFF_ANI_5_ADDR				(IMG_PWROFF_ANI_4_END+IMG_OFFSET)
#define IMG_PWROFF_ANI_5_SIZE				(29776)
#define IMG_PWROFF_ANI_5_END				(IMG_PWROFF_ANI_5_ADDR+IMG_PWROFF_ANI_5_SIZE)
#define IMG_PWROFF_ANI_6_ADDR				(IMG_PWROFF_ANI_5_END+IMG_OFFSET)
#define IMG_PWROFF_ANI_6_SIZE				(29776)
#define IMG_PWROFF_ANI_6_END				(IMG_PWROFF_ANI_6_ADDR+IMG_PWROFF_ANI_6_SIZE)
#define IMG_PWROFF_ANI_7_ADDR				(IMG_PWROFF_ANI_6_END+IMG_OFFSET)
#define IMG_PWROFF_ANI_7_SIZE				(29776)
#define IMG_PWROFF_ANI_7_END				(IMG_PWROFF_ANI_7_ADDR+IMG_PWROFF_ANI_7_SIZE)
#define IMG_PWROFF_ANI_8_ADDR				(IMG_PWROFF_ANI_7_END+IMG_OFFSET)
#define IMG_PWROFF_ANI_8_SIZE				(29776)
#define IMG_PWROFF_ANI_8_END				(IMG_PWROFF_ANI_8_ADDR+IMG_PWROFF_ANI_8_SIZE)
#define IMG_PWROFF_BG_ADDR					(IMG_PWROFF_ANI_8_END+IMG_OFFSET)
#define IMG_PWROFF_BG_SIZE					(115208)
#define IMG_PWROFF_BG_END					(IMG_PWROFF_BG_ADDR+IMG_PWROFF_BG_SIZE)
#define IMG_PWROFF_BUTTON_ADDR				(IMG_PWROFF_BG_END+IMG_OFFSET)
#define IMG_PWROFF_BUTTON_SIZE				(12808)
#define IMG_PWROFF_BUTTON_END				(IMG_PWROFF_BUTTON_ADDR+IMG_PWROFF_BUTTON_SIZE)
#define IMG_PWROFF_NO_ADDR					(IMG_PWROFF_BUTTON_END+IMG_OFFSET)
#define IMG_PWROFF_NO_SIZE					(3208)
#define IMG_PWROFF_NO_END					(IMG_PWROFF_NO_ADDR+IMG_PWROFF_NO_SIZE)
#define IMG_PWROFF_RUNNING_STR_ADDR			(IMG_PWROFF_NO_END+IMG_OFFSET)
#define IMG_PWROFF_RUNNING_STR_SIZE			(8626)
#define IMG_PWROFF_RUNNING_STR_END			(IMG_PWROFF_RUNNING_STR_ADDR+IMG_PWROFF_RUNNING_STR_SIZE)
#define IMG_PWROFF_STR_ADDR					(IMG_PWROFF_RUNNING_STR_END+IMG_OFFSET)
#define IMG_PWROFF_STR_SIZE					(5732)
#define IMG_PWROFF_STR_END					(IMG_PWROFF_STR_ADDR+IMG_PWROFF_STR_SIZE)
#define IMG_PWROFF_YES_ADDR					(IMG_PWROFF_STR_END+IMG_OFFSET)
#define IMG_PWROFF_YES_SIZE					(3208)
#define IMG_PWROFF_YES_END					(IMG_PWROFF_YES_ADDR+IMG_PWROFF_YES_SIZE)
//power on
#define IMG_PWRON_ANI_1_ADDR				(IMG_PWROFF_YES_END+IMG_OFFSET)
#define IMG_PWRON_ANI_1_SIZE				(13388)
#define IMG_PWRON_ANI_1_END					(IMG_PWRON_ANI_1_ADDR+IMG_PWRON_ANI_1_SIZE)
#define IMG_PWRON_ANI_2_ADDR				(IMG_PWRON_ANI_1_END+IMG_OFFSET)
#define IMG_PWRON_ANI_2_SIZE				(13388)
#define IMG_PWRON_ANI_2_END					(IMG_PWRON_ANI_2_ADDR+IMG_PWRON_ANI_2_SIZE)
#define IMG_PWRON_ANI_3_ADDR				(IMG_PWRON_ANI_2_END+IMG_OFFSET)
#define IMG_PWRON_ANI_3_SIZE				(13388)
#define IMG_PWRON_ANI_3_END					(IMG_PWRON_ANI_3_ADDR+IMG_PWRON_ANI_3_SIZE)
#define IMG_PWRON_ANI_4_ADDR				(IMG_PWRON_ANI_3_END+IMG_OFFSET)
#define IMG_PWRON_ANI_4_SIZE				(13388)
#define IMG_PWRON_ANI_4_END					(IMG_PWRON_ANI_4_ADDR+IMG_PWRON_ANI_4_SIZE)
#define IMG_PWRON_ANI_5_ADDR				(IMG_PWRON_ANI_4_END+IMG_OFFSET)
#define IMG_PWRON_ANI_5_SIZE				(13388)
#define IMG_PWRON_ANI_5_END					(IMG_PWRON_ANI_5_ADDR+IMG_PWRON_ANI_5_SIZE)
#define IMG_PWRON_ANI_6_ADDR				(IMG_PWRON_ANI_5_END+IMG_OFFSET)
#define IMG_PWRON_ANI_6_SIZE				(13388)
#define IMG_PWRON_ANI_6_END					(IMG_PWRON_ANI_6_ADDR+IMG_PWRON_ANI_6_SIZE)
#define IMG_PWRON_BG_ADDR					(IMG_PWRON_ANI_6_END+IMG_OFFSET)
#define IMG_PWRON_BG_SIZE					(115208)
#define IMG_PWRON_BG_END					(IMG_PWRON_BG_ADDR+IMG_PWRON_BG_SIZE)
#define IMG_PWRON_STR_ADDR					(IMG_PWRON_BG_END+IMG_OFFSET)
#define IMG_PWRON_STR_SIZE					(9908)
#define IMG_PWRON_STR_END					(IMG_PWRON_STR_ADDR+IMG_PWRON_STR_SIZE)
//3 dot gif
#define IMG_RUNNING_ANI_1_ADDR				(IMG_PWRON_STR_END+IMG_OFFSET)
#define IMG_RUNNING_ANI_1_SIZE				(2114)
#define IMG_RUNNING_ANI_1_END				(IMG_RUNNING_ANI_1_ADDR+IMG_RUNNING_ANI_1_SIZE)
#define IMG_RUNNING_ANI_2_ADDR				(IMG_RUNNING_ANI_1_END+IMG_OFFSET)
#define IMG_RUNNING_ANI_2_SIZE				(2114)
#define IMG_RUNNING_ANI_2_END				(IMG_RUNNING_ANI_2_ADDR+IMG_RUNNING_ANI_2_SIZE)
#define IMG_RUNNING_ANI_3_ADDR				(IMG_RUNNING_ANI_2_END+IMG_OFFSET)
#define IMG_RUNNING_ANI_3_SIZE				(2114)
#define IMG_RUNNING_ANI_3_END				(IMG_RUNNING_ANI_3_ADDR+IMG_RUNNING_ANI_3_SIZE)
#define IMG_RUNNING_ANI_4_ADDR				(IMG_RUNNING_ANI_3_END+IMG_OFFSET)
#define IMG_RUNNING_ANI_4_SIZE				(2114)
#define IMG_RUNNING_ANI_4_END				(IMG_RUNNING_ANI_4_ADDR+IMG_RUNNING_ANI_4_SIZE)
//signal
#define IMG_SIG_0_ADDR						(IMG_RUNNING_ANI_4_END+IMG_OFFSET)
#define IMG_SIG_0_SIZE						(1744)
#define IMG_SIG_0_END						(IMG_SIG_0_ADDR+IMG_SIG_0_SIZE)
#define IMG_SIG_1_ADDR						(IMG_SIG_0_END+IMG_OFFSET)
#define IMG_SIG_1_SIZE						(1744)
#define IMG_SIG_1_END						(IMG_SIG_1_ADDR+IMG_SIG_1_SIZE)
#define IMG_SIG_2_ADDR						(IMG_SIG_1_END+IMG_OFFSET)
#define IMG_SIG_2_SIZE						(1744)
#define IMG_SIG_2_END						(IMG_SIG_2_ADDR+IMG_SIG_2_SIZE)
#define IMG_SIG_3_ADDR						(IMG_SIG_2_END+IMG_OFFSET)
#define IMG_SIG_3_SIZE						(1744)
#define IMG_SIG_3_END						(IMG_SIG_3_ADDR+IMG_SIG_3_SIZE)
#define IMG_SIG_4_ADDR						(IMG_SIG_3_END+IMG_OFFSET)
#define IMG_SIG_4_SIZE						(1744)
#define IMG_SIG_4_END						(IMG_SIG_4_ADDR+IMG_SIG_4_SIZE)
//sim information
#define IMG_SIM_ICCID_ADDR					(IMG_SIG_4_END+IMG_OFFSET)
#define IMG_SIM_ICCID_SIZE					(2524)
#define IMG_SIM_ICCID_END					(IMG_SIM_ICCID_ADDR+IMG_SIM_ICCID_SIZE)
#define IMG_SIM_IMSI_ADDR					(IMG_SIM_ICCID_END+IMG_OFFSET)
#define IMG_SIM_IMSI_SIZE					(2388)
#define IMG_SIM_IMSI_END					(IMG_SIM_IMSI_ADDR+IMG_SIM_IMSI_SIZE)
//sleep
#define IMG_SLEEP_ANI_1_ADDR				(IMG_SIM_IMSI_END+IMG_OFFSET)
#define IMG_SLEEP_ANI_1_SIZE				(4608)
#define IMG_SLEEP_ANI_1_END					(IMG_SLEEP_ANI_1_ADDR+IMG_SLEEP_ANI_1_SIZE)
#define IMG_SLEEP_ANI_2_ADDR				(IMG_SLEEP_ANI_1_END+IMG_OFFSET)
#define IMG_SLEEP_ANI_2_SIZE				(4608)
#define IMG_SLEEP_ANI_2_END					(IMG_SLEEP_ANI_2_ADDR+IMG_SLEEP_ANI_2_SIZE)
#define IMG_SLEEP_ANI_3_ADDR				(IMG_SLEEP_ANI_2_END+IMG_OFFSET)
#define IMG_SLEEP_ANI_3_SIZE				(4608)
#define IMG_SLEEP_ANI_3_END					(IMG_SLEEP_ANI_3_ADDR+IMG_SLEEP_ANI_3_SIZE)
#define IMG_SLEEP_DEEP_ICON_ADDR			(IMG_SLEEP_ANI_3_END+IMG_OFFSET)
#define IMG_SLEEP_DEEP_ICON_SIZE			(2600)
#define IMG_SLEEP_DEEP_ICON_END				(IMG_SLEEP_DEEP_ICON_ADDR+IMG_SLEEP_DEEP_ICON_SIZE)
#define IMG_SLEEP_HOUR_ADDR					(IMG_SLEEP_DEEP_ICON_END+IMG_OFFSET)
#define IMG_SLEEP_HOUR_SIZE					(844)
#define IMG_SLEEP_HOUR_END					(IMG_SLEEP_HOUR_ADDR+IMG_SLEEP_HOUR_SIZE)
#define IMG_SLEEP_LIGHT_ICON_ADDR			(IMG_SLEEP_HOUR_END+IMG_OFFSET)
#define IMG_SLEEP_LIGHT_ICON_SIZE			(2600)
#define IMG_SLEEP_LIGHT_ICON_END			(IMG_SLEEP_LIGHT_ICON_ADDR+IMG_SLEEP_LIGHT_ICON_SIZE)
#define IMG_SLEEP_LINE_ADDR					(IMG_SLEEP_LIGHT_ICON_END+IMG_OFFSET)
#define IMG_SLEEP_LINE_SIZE					(712)
#define IMG_SLEEP_LINE_END					(IMG_SLEEP_LINE_ADDR+IMG_SLEEP_LINE_SIZE)
#define IMG_SLEEP_MIN_ADDR					(IMG_SLEEP_LINE_END+IMG_OFFSET)
#define IMG_SLEEP_MIN_SIZE					(1460)
#define IMG_SLEEP_MIN_END					(IMG_SLEEP_MIN_ADDR+IMG_SLEEP_MIN_SIZE)
//sos
#define IMG_SOS_ANI_1_ADDR					(IMG_SLEEP_MIN_END+IMG_OFFSET)
#define IMG_SOS_ANI_1_SIZE					(115208)
#define IMG_SOS_ANI_1_END					(IMG_SOS_ANI_1_ADDR+IMG_SOS_ANI_1_SIZE)
#define IMG_SOS_ANI_2_ADDR					(IMG_SOS_ANI_1_END+IMG_OFFSET)
#define IMG_SOS_ANI_2_SIZE					(115208)
#define IMG_SOS_ANI_2_END					(IMG_SOS_ANI_2_ADDR+IMG_SOS_ANI_2_SIZE)
#define IMG_SOS_ANI_3_ADDR					(IMG_SOS_ANI_2_END+IMG_OFFSET)
#define IMG_SOS_ANI_3_SIZE					(115208)
#define IMG_SOS_ANI_3_END					(IMG_SOS_ANI_3_ADDR+IMG_SOS_ANI_3_SIZE)
#define IMG_SOS_ANI_4_ADDR					(IMG_SOS_ANI_3_END+IMG_OFFSET)
#define IMG_SOS_ANI_4_SIZE					(115208)
#define IMG_SOS_ANI_4_END					(IMG_SOS_ANI_4_ADDR+IMG_SOS_ANI_4_SIZE)
//step
#define IMG_STEP_ANI_1_ADDR					(IMG_SOS_ANI_4_END+IMG_OFFSET)
#define IMG_STEP_ANI_1_SIZE					(4036)
#define IMG_STEP_ANI_1_END					(IMG_STEP_ANI_1_ADDR+IMG_STEP_ANI_1_SIZE)
#define IMG_STEP_ANI_2_ADDR					(IMG_STEP_ANI_1_END+IMG_OFFSET)
#define IMG_STEP_ANI_2_SIZE					(4036)
#define IMG_STEP_ANI_2_END					(IMG_STEP_ANI_2_ADDR+IMG_STEP_ANI_2_SIZE)
#define IMG_STEP_CAL_ICON_ADDR				(IMG_STEP_ANI_2_END+IMG_OFFSET)
#define IMG_STEP_CAL_ICON_SIZE				(2024)
#define IMG_STEP_CAL_ICON_END				(IMG_STEP_CAL_ICON_ADDR+IMG_STEP_CAL_ICON_SIZE)
#define IMG_STEP_DIS_ICON_ADDR				(IMG_STEP_CAL_ICON_END+IMG_OFFSET)
#define IMG_STEP_DIS_ICON_SIZE				(2096)
#define IMG_STEP_DIS_ICON_END				(IMG_STEP_DIS_ICON_ADDR+IMG_STEP_DIS_ICON_SIZE)
#define IMG_STEP_ICON_ADDR					(IMG_STEP_DIS_ICON_END+IMG_OFFSET)
#define IMG_STEP_ICON_SIZE					(2208)
#define IMG_STEP_ICON_END					(IMG_STEP_ICON_ADDR+IMG_STEP_ICON_SIZE)
#define IMG_STEP_KCAL_ADDR					(IMG_STEP_ICON_END+IMG_OFFSET)
#define IMG_STEP_KCAL_SIZE					(708)
#define IMG_STEP_KCAL_END					(IMG_STEP_KCAL_ADDR+IMG_STEP_KCAL_SIZE)
#define IMG_STEP_KM_ADDR					(IMG_STEP_KCAL_END+IMG_OFFSET)
#define IMG_STEP_KM_SIZE					(484)
#define IMG_STEP_KM_END						(IMG_STEP_KM_ADDR+IMG_STEP_KM_SIZE)
#define IMG_STEP_LINE_ADDR					(IMG_STEP_KM_END+IMG_OFFSET)
#define IMG_STEP_LINE_SIZE					(668)
#define IMG_STEP_LINE_END					(IMG_STEP_LINE_ADDR+IMG_STEP_LINE_SIZE)
//sync
#define IMG_SYNC_ERR_ADDR					(IMG_STEP_LINE_END+IMG_OFFSET)
#define IMG_SYNC_ERR_SIZE					(24868)
#define IMG_SYNC_ERR_END					(IMG_SYNC_ERR_ADDR+IMG_SYNC_ERR_SIZE)
#define IMG_SYNC_FINISH_ADDR				(IMG_SYNC_ERR_END+IMG_OFFSET)
#define IMG_SYNC_FINISH_SIZE				(24868)
#define IMG_SYNC_FINISH_END					(IMG_SYNC_FINISH_ADDR+IMG_SYNC_FINISH_SIZE)
#define IMG_SYNC_LOGO_ADDR					(IMG_SYNC_FINISH_END+IMG_OFFSET)
#define IMG_SYNC_LOGO_SIZE					(20808)
#define IMG_SYNC_LOGO_END					(IMG_SYNC_LOGO_ADDR+IMG_SYNC_LOGO_SIZE)
#define IMG_SYNC_STR_ADDR					(IMG_SYNC_LOGO_END+IMG_OFFSET)
#define IMG_SYNC_STR_SIZE					(8288)
#define IMG_SYNC_STR_END					(IMG_SYNC_STR_ADDR+IMG_SYNC_STR_SIZE)
//temperature
#define IMG_TEMP_BODY_ADDR					(IMG_SYNC_STR_END+IMG_OFFSET)
#define IMG_TEMP_BODY_SIZE					(2312)
#define IMG_TEMP_BODY_END					(IMG_TEMP_BODY_ADDR+IMG_TEMP_BODY_SIZE)
#define IMG_TEMP_ICON_C_ADDR				(IMG_TEMP_BODY_END+IMG_OFFSET)
#define IMG_TEMP_ICON_C_SIZE				(26268)
#define IMG_TEMP_ICON_C_END					(IMG_TEMP_ICON_C_ADDR+IMG_TEMP_ICON_C_SIZE)
#define IMG_TEMP_ICON_F_ADDR				(IMG_TEMP_ICON_C_END+IMG_OFFSET)
#define IMG_TEMP_ICON_F_SIZE				(26268)
#define IMG_TEMP_ICON_F_END					(IMG_TEMP_ICON_F_ADDR+IMG_TEMP_ICON_F_SIZE)
#define IMG_TEMP_SKIN_ADDR					(IMG_TEMP_ICON_F_END+IMG_OFFSET)
#define IMG_TEMP_SKIN_SIZE					(944)
#define IMG_TEMP_SKIN_END					(IMG_TEMP_SKIN_ADDR+IMG_TEMP_SKIN_SIZE)
#define IMG_TEMP_UNIT_C_ADDR				(IMG_TEMP_SKIN_END+IMG_OFFSET)
#define IMG_TEMP_UNIT_C_SIZE				(520)
#define IMG_TEMP_UNIT_C_END					(IMG_TEMP_UNIT_C_ADDR+IMG_TEMP_UNIT_C_SIZE)
#define IMG_TEMP_UNIT_F_ADDR				(IMG_TEMP_UNIT_C_END+IMG_OFFSET)
#define IMG_TEMP_UNIT_F_SIZE				(520)
#define IMG_TEMP_UNIT_F_END					(IMG_TEMP_UNIT_F_ADDR+IMG_TEMP_UNIT_F_SIZE)
//wrist off
#define IMG_WRIST_OFF_ICON_ADDR				(IMG_TEMP_UNIT_F_END+IMG_OFFSET)
#define IMG_WRIST_OFF_ICON_SIZE				(23372)
#define IMG_WRIST_OFF_ICON_END				(IMG_WRIST_OFF_ICON_ADDR+IMG_WRIST_OFF_ICON_SIZE)

#define IMG_END_ADDR			0x3FFFFF

//FONT在flash里占用3M的空间(0x400000~0x6FFFFF)
#define FONT_START_ADDR			0x400000
#define FONT_OFFSET				0

#define FONT_ASC_1608_ADDR		FONT_START_ADDR
#define FONT_ASC_1608_WIDTH		16
#define FONT_ASC_1608_SIZE 		(96*16)
#define FONT_ASC_1608_END		(FONT_ASC_1608_ADDR+FONT_ASC_1608_SIZE)

#define FONT_ASC_2412_ADDR		(FONT_ASC_1608_END+FONT_OFFSET)
#define FONT_ASC_2412_WIDTH		48
#define FONT_ASC_2412_SIZE 		(96*48)
#define FONT_ASC_2412_END		(FONT_ASC_2412_ADDR+FONT_ASC_2412_SIZE)

#define FONT_ASC_3216_ADDR		(FONT_ASC_2412_END+FONT_OFFSET)
#define FONT_ASC_3216_WIDTH		64
#define FONT_ASC_3216_SIZE 		(96*64)
#define FONT_ASC_3216_END		(FONT_ASC_3216_ADDR+FONT_ASC_3216_SIZE)

#define FONT_ASC_4824_ADDR		(FONT_ASC_3216_END+FONT_OFFSET)
#define FONT_ASC_4824_WIDTH		144
#define FONT_ASC_4824_SIZE 		(96*144)
#define FONT_ASC_4824_END		(FONT_ASC_4824_ADDR+FONT_ASC_4824_SIZE)

#define FONT_ASC_6432_ADDR		(FONT_ASC_4824_END+FONT_OFFSET)
#define FONT_ASC_6432_WIDTH		256
#define FONT_ASC_6432_SIZE 		(96*255)
#define FONT_ASC_6432_END		(FONT_ASC_6432_ADDR+FONT_ASC_6432_SIZE)

#define FONT_CHN_SM_1616_ADDR	(FONT_ASC_6432_END+FONT_OFFSET)
#define FONT_CHN_SM_1616_WIDTH	32
#define FONT_CHN_SM_1616_SIZE 	(8178*32)
#define FONT_CHN_SM_1616_END	(FONT_CHN_SM_1616_ADDR+FONT_CHN_SM_1616_SIZE)

#define FONT_CHN_SM_2424_ADDR	(FONT_CHN_SM_1616_END+FONT_OFFSET)
#define FONT_CHN_SM_2424_WIDTH	72
#define FONT_CHN_SM_2424_SIZE 	(8178*72)
#define FONT_CHN_SM_2424_END	(FONT_CHN_SM_2424_ADDR+FONT_CHN_SM_2424_SIZE)

#define FONT_CHN_SM_3232_ADDR	(FONT_CHN_SM_2424_END+FONT_OFFSET)
#define FONT_CHN_SM_3232_WIDTH	128
#define FONT_CHN_SM_3232_SIZE 	(8178*128)
#define FONT_CHN_SM_3232_END	(FONT_CHN_SM_3232_ADDR+FONT_CHN_SM_3232_SIZE)

#define FONT_RM_ASC_16_ADDR		(FONT_CHN_SM_3232_END+FONT_OFFSET)
#define FONT_RM_ASC_16_SIZE 	(6768)
#define FONT_RM_ASC_16_END		(FONT_RM_ASC_16_ADDR+FONT_RM_ASC_16_SIZE)

#define FONT_RM_JIS_16_ADDR		(FONT_RM_ASC_16_END+FONT_OFFSET)
#define FONT_RM_JIS_16_SIZE		(360976)
#define FONT_RM_JIS_16_END		(FONT_RM_JIS_16_ADDR+FONT_RM_JIS_16_SIZE)

#define FONT_RM_UNI_16_ADDR		(FONT_RM_JIS_16_END+FONT_OFFSET)
#define FONT_RM_UNI_16_SIZE		(617952)
#define FONT_RM_UNI_16_END		(FONT_RM_UNI_16_ADDR+FONT_RM_UNI_16_SIZE)

#define FONT_RM_UNI_24_ADDR		(FONT_RM_UNI_16_END+FONT_OFFSET)
#define FONT_RM_UNI_24_SIZE		(976388)
#define FONT_RM_UNI_24_END		(FONT_RM_UNI_24_ADDR+FONT_RM_UNI_24_SIZE)

#define FONT_END_ADDR			0x6FFFFF

//资料 flash里占用1M的空间(0x700000~0x7FFFFF)
#define DATA_START_ADDR			0x700000
#define DATA_OFFSET				0

#define PPG_ALGO_FW_ADDR		DATA_START_ADDR
#define PPG_ALGO_FW_SIZE 		(279152)
#define PPG_ALGO_FW_END			(PPG_ALGO_FW_ADDR+PPG_ALGO_FW_SIZE)

#define DATA_END_ADDR			0x7FFFFF


void SPI_Flash_Init(void);
uint16_t SpiFlash_ReadID(void);

uint8_t SpiFlash_Write_Page(uint8_t *pBuffer, uint32_t WriteAddr, uint32_t size);
uint8_t SpiFlash_Read(uint8_t *pBuffer,uint32_t ReadAddr,uint32_t size);
void SPIFlash_Erase_Sector(uint32_t SecAddr);
void SPIFlash_Erase_Chip(void);
uint8_t SpiFlash_Write_Buf(uint8_t *pBuffer, uint32_t WriteAddr, uint32_t WriteBytesNum);
extern void test_flash(void);

#endif/*__EXTERNAL_FLASH_H__*/
