/****************************************Copyright (c)************************************************
** File Name:			    max86176.H
** Descriptions:			PPG AFE process head file
** Created By:				xie biao
** Created Date:			2025-07-07
** Modified Date:      		2025-07-07 
** Version:			    	V1.0
******************************************************************************************************/
#ifndef __MAX86176_H__
#define __MAX86176_H__

#if DT_NODE_HAS_STATUS(DT_NODELABEL(spi3), okay)
#define PPG_DEV DT_NODELABEL(spi3)
#else
#error "spi3 devicetree node is disabled"
#define PPG_DEV	""
#endif

#if DT_NODE_HAS_STATUS(DT_NODELABEL(gpio0), okay)
#define PPG_PORT DT_NODELABEL(gpio0)
#else
#error "gpio0 devicetree node is disabled"
#define PPG_PORT	""
#endif

#define PPG_CS_PIN			0
#define PPG_INT1_PIN		2
#define PPG_INT2_PIN		3

#define MAX86176_PART_ID	0x39

// Section - FIFO
#define FIFO_WRITE_POINTER_REGISTER	0x08
#define FIFO_WR_PTR_MASK	0xFF
#define FIFO_WR_PTR_SHIFT	0

#define FIFO_READ_POINTER_REGISTER	0x09
#define FIFO_RD_PTR_MASK	0xFF
#define FIFO_RD_PTR_SHIFT	0

#define FIFO_COUNTER_1_REGISTER	0x0A
#define FIFO_DATA_COUNT_MSB_MASK	0x80
#define FIFO_DATA_COUNT_MSB_SHIFT	7
#define OVF_COUNTER_MASK	0x7F
#define OVF_COUNTER_SHIFT	0

#define FIFO_COUNTER_2_REGISTER	0x0B
#define FIFO_DATA_COUNT_LSB_MASK	0xFF
#define FIFO_DATA_COUNT_LSB_SHIFT	0

#define FIFO_DATA_REGISTER_REGISTER	0x0C
#define FIFO_DATA_MASK	0xFF
#define FIFO_DATA_SHIFT	0

#define FIFO_CONFIGURATION_1_REGISTER	0x0D
#define FIFO_A_FULL_MASK	0xFF
#define FIFO_A_FULL_SHIFT	0

#define FIFO_CONFIGURATION_2_REGISTER	0x0E
#define FIFO_MARK_MASK	0x20
#define FIFO_MARK_SHIFT	5
#define FLUSH_FIFO_MASK	0x10
#define FLUSH_FIFO_SHIFT	4
#define FIFO_STAT_CLR_MASK	0x08
#define FIFO_STAT_CLR_SHIFT	3
#define A_FULL_TYPE_MASK	0x04
#define A_FULL_TYPE_SHIFT	2
#define FIFO_RO_MASK	0x02
#define FIFO_RO_SHIFT	1

// Section - System Control
#define SYSTEM_CONFIGURATION_1_REGISTER	0x10
#define TIMING_SYS_RESET_MASK	0x80
#define TIMING_SYS_RESET_SHIFT	7
#define SW_FORCE_SYNC_MASK	0x40
#define SW_FORCE_SYNC_SHIFT	6
#define SYNC_MODE_MASK	0x30
#define SYNC_MODE_SHIFT	4
#define PPG2_PWRDN_MASK	0x08
#define PPG2_PWRDN_SHIFT	3
#define PPG1_PWRDN_MASK	0x04
#define PPG1_PWRDN_SHIFT	2
#define SHDN_MASK	0x02
#define SHDN_SHIFT	1
#define RESET_MASK	0x01
#define RESET_SHIFT	0

#define SYSTEM_CONFIGURATION_2_REGISTER	0x11
#define MEAS8_EN_MASK	0x80
#define MEAS8_EN_SHIFT	7
#define MEAS7_EN_MASK	0x40
#define MEAS7_EN_SHIFT	6
#define MEAS6_EN_MASK	0x20
#define MEAS6_EN_SHIFT	5
#define MEAS5_EN_MASK	0x10
#define MEAS5_EN_SHIFT	4
#define MEAS4_EN_MASK	0x08
#define MEAS4_EN_SHIFT	3
#define MEAS3_EN_MASK	0x04
#define MEAS3_EN_SHIFT	2
#define MEAS2_EN_MASK	0x02
#define MEAS2_EN_SHIFT	1
#define MEAS1_EN_MASK	0x01
#define MEAS1_EN_SHIFT	0

#define SYSTEM_CONFIGURATION_3_REGISTER	0x12
#define MEAS9_EN_MASK	0x80
#define MEAS9_EN_SHIFT	7
#define EN_VDD_OOR_MASK	0x40
#define EN_VDD_OOR_SHIFT	6
#define ALC_DISABLE_MASK	0x10
#define ALC_DISABLE_SHIFT	4
#define MASTER_MASK	0x08
#define MASTER_SHIFT	3
#define PPG_TIMING_DATA_MASK	0x04
#define PPG_TIMING_DATA_SHIFT	2
#define COLLECT_RAW_DATA_MASK	0x02
#define COLLECT_RAW_DATA_SHIFT	1
#define MEAS1_CONFIG_SEL_MASK	0x01
#define MEAS1_CONFIG_SEL_SHIFT	0

#define SYSTEM_CONFIGURATION_4_REGISTER	0x13
#define SAMP_SYNC_FREQ_MASK	0x7C
#define SAMP_SYNC_FREQ_SHIFT	2
#define PROX_DATA_EN_MASK	0x02
#define PROX_DATA_EN_SHIFT	1
#define PROX_AUTO_MASK	0x01
#define PROX_AUTO_SHIFT	0

#define PHOTO_DIODE_BIAS_REGISTER	0x14
#define PD4_BIAS_MASK	0xC0
#define PD4_BIAS_SHIFT	6
#define PD3_BIAS_MASK	0x30
#define PD3_BIAS_SHIFT	4
#define PD2_BIAS_MASK	0x0C
#define PD2_BIAS_SHIFT	2
#define PD1_BIAS_MASK	0x03
#define PD1_BIAS_SHIFT	0

#define PIN_FUNCTIONAL_CONFIGURATION_REGISTER	0x15
#define INT2_FCFG_MASK	0x18
#define INT2_FCFG_SHIFT	3
#define INT1_FCFG_MASK	0x06
#define INT1_FCFG_SHIFT	1
#define TRIG_ICFG_MASK	0x01
#define TRIG_ICFG_SHIFT	0

#define OUTPUT_PIN_CONFIGURATION_REGISTER	0x16
#define INT2_OCFG_MASK	0x18
#define INT2_OCFG_SHIFT	3
#define INT1_OCFG_MASK	0x06
#define INT1_OCFG_SHIFT	1

#define I2C_BROADCAST_ADDRESS_REGISTER	0x17
#define I2C_BCAST_ADDR_MASK	0xFE
#define I2C_BCAST_ADDR_SHIFT	1
#define I2C_BCAST_EN_MASK	0x01
#define I2C_BCAST_EN_SHIFT	0

// Section - PLL
#define PLL_CONFIGURATION_1_REGISTER	0x18
#define PLL_LOCK_WNDW_MASK	0x80
#define PLL_LOCK_WNDW_SHIFT	7
#define PLL_EN_MASK	0x01
#define PLL_EN_SHIFT	0

#define PLL_CONFIGURATION_2_REGISTER	0x19
#define NDIV_MSB_MASK	0x80
#define NDIV_MSB_SHIFT	7
#define MDIV_MASK	0x3F
#define MDIV_SHIFT	0

#define PLL_CONFIGURATION_3_REGISTER	0x1A
#define NDIV_LSB_MASK	0xFF
#define NDIV_LSB_SHIFT	0

// Section - PPG Frame Rate Clock
#define FR_CLOCK_FREQUENCY_SELECT_REGISTER	0x1C
#define FR_CLK_SEL_MASK	0x20
#define FR_CLK_SEL_SHIFT	5
#define FR_CLK_FINE_TUNE_MASK	0x1F
#define FR_CLK_FINE_TUNE_SHIFT	0

#define FR_CLOCK_DIVIDER_MSB_REGISTER	0x1D
#define FR_CLK_DIV_MSB_MASK	0x7F
#define FR_CLK_DIV_MSB_SHIFT	0

#define FR_CLOCK_DIVIDER_LSB_REGISTER	0x1E
#define FR_CLK_DIV_LSB_MASK	0xFF
#define FR_CLK_DIV_LSB_SHIFT	0

// Section - PPG MEAS1 Setup
#define MEAS1_SELECTS_REGISTER	0x20
#define MEAS1_AMB_MASK	0x40
#define MEAS1_AMB_SHIFT	6
#define MEAS1_DRVB_MASK	0x38
#define MEAS1_DRVB_SHIFT	3
#define MEAS1_DRVA_MASK	0x07
#define MEAS1_DRVA_SHIFT	0

#define MEAS1_CONFIGURATION_1_REGISTER	0x21
#define MEAS1_TINT_MASK	0x18
#define MEAS1_TINT_SHIFT	3
#define MEAS1_AVER_MASK	0x07
#define MEAS1_AVER_SHIFT	0

#define MEAS1_CONFIGURATION_2_REGISTER	0x22
#define MEAS1_SINC3_SEL_MASK	0x80
#define MEAS1_SINC3_SEL_SHIFT	7
#define MEAS1_FILT_SEL_MASK	0x40
#define MEAS1_FILT_SEL_SHIFT	6
#define MEAS1_LED_RGE_MASK	0x30
#define MEAS1_LED_RGE_SHIFT	4
#define MEAS1_PPG2_ADC_RGE_MASK	0x0C
#define MEAS1_PPG2_ADC_RGE_SHIFT	2
#define MEAS1_PPG1_ADC_RGE_MASK	0x03
#define MEAS1_PPG1_ADC_RGE_SHIFT	0

#define MEAS1_CONFIGURATION_3_REGISTER	0x23
#define MEAS1_PD_SETLNG_MASK	0xC0
#define MEAS1_PD_SETLNG_SHIFT	6
#define MEAS1_LED_SETLNG_MASK	0x30
#define MEAS1_LED_SETLNG_SHIFT	4
#define MEAS1_PPG2_DACOFF_MASK	0x0C
#define MEAS1_PPG2_DACOFF_SHIFT	2
#define MEAS1_PPG1_DACOFF_MASK	0x03
#define MEAS1_PPG1_DACOFF_SHIFT	0

#define MEAS1_CONFIGURATION_4_REGISTER	0x24
#define MEAS1_BUFCHAN_MASK	0x40
#define MEAS1_BUFCHAN_SHIFT	6
#define MEAS1_PPG_GAIN_MASK	0x30
#define MEAS1_PPG_GAIN_SHIFT	4
#define MEAS1_PPG2_PDSEL_MASK	0x0C
#define MEAS1_PPG2_PDSEL_SHIFT	2
#define MEAS1_PPG1_PDSEL_MASK	0x03
#define MEAS1_PPG1_PDSEL_SHIFT	0

#define MEAS1_LEDA_CURRENT_REGISTER	0x25
#define MEAS1_DRVA_PA_MASK	0xFF
#define MEAS1_DRVA_PA_SHIFT	0

#define MEAS1_LEDB_CURRENT_REGISTER	0x26
#define MEAS1_DRVB_PA_MASK	0xFF
#define MEAS1_DRVB_PA_SHIFT	0

// Section - PPG MEAS2 Setup
#define MEAS2_SELECTS_REGISTER	0x28
#define MEAS2_AMB_MASK	0x40
#define MEAS2_AMB_SHIFT	6
#define MEAS2_DRVB_MASK	0x38
#define MEAS2_DRVB_SHIFT	3
#define MEAS2_DRVA_MASK	0x07
#define MEAS2_DRVA_SHIFT	0

#define MEAS2_CONFIGURATION_1_REGISTER	0x29
#define MEAS2_TINT_MASK	0x18
#define MEAS2_TINT_SHIFT	3
#define MEAS2_AVER_MASK	0x07
#define MEAS2_AVER_SHIFT	0

#define MEAS2_CONFIGURATION_2_REGISTER	0x2A
#define MEAS2_SINC3_SEL_MASK	0x80
#define MEAS2_SINC3_SEL_SHIFT	7
#define MEAS2_FILT_SEL_MASK	0x40
#define MEAS2_FILT_SEL_SHIFT	6
#define MEAS2_LED_RGE_MASK	0x30
#define MEAS2_LED_RGE_SHIFT	4
#define MEAS2_PPG2_ADC_RGE_MASK	0x0C
#define MEAS2_PPG2_ADC_RGE_SHIFT	2
#define MEAS2_PPG1_ADC_RGE_MASK	0x03
#define MEAS2_PPG1_ADC_RGE_SHIFT	0

#define MEAS2_CONFIGURATION_3_REGISTER	0x2B
#define MEAS2_PD_SETLNG_MASK	0xC0
#define MEAS2_PD_SETLNG_SHIFT	6
#define MEAS2_LED_SETLNG_MASK	0x30
#define MEAS2_LED_SETLNG_SHIFT	4
#define MEAS2_PPG2_DACOFF_MASK	0x0C
#define MEAS2_PPG2_DACOFF_SHIFT	2
#define MEAS2_PPG1_DACOFF_MASK	0x03
#define MEAS2_PPG1_DACOFF_SHIFT	0

#define MEAS2_CONFIGURATION_4_REGISTER	0x2C
#define MEAS2_BUFCHAN_MASK	0x40
#define MEAS2_BUFCHAN_SHIFT	6
#define MEAS2_PPG_GAIN_MASK	0x30
#define MEAS2_PPG_GAIN_SHIFT	4
#define MEAS2_PPG2_PDSEL_MASK	0x0C
#define MEAS2_PPG2_PDSEL_SHIFT	2
#define MEAS2_PPG1_PDSEL_MASK	0x03
#define MEAS2_PPG1_PDSEL_SHIFT	0

#define MEAS2_LEDA_CURRENT_REGISTER	0x2D
#define MEAS2_DRVA_PA_MASK	0xFF
#define MEAS2_DRVA_PA_SHIFT	0

#define MEAS2_LEDB_CURRENT_REGISTER	0x2E
#define MEAS2_DRVB_PA_MASK	0xFF
#define MEAS2_DRVB_PA_SHIFT	0

// Section - PPG MEAS3 Setup
#define MEAS3_SELECTS_REGISTER	0x30
#define MEAS3_AMB_MASK	0x40
#define MEAS3_AMB_SHIFT	6
#define MEAS3_DRVB_MASK	0x38
#define MEAS3_DRVB_SHIFT	3
#define MEAS3_DRVA_MASK	0x07
#define MEAS3_DRVA_SHIFT	0

#define MEAS3_CONFIGURATION_1_REGISTER	0x31
#define MEAS3_TINT_MASK	0x18
#define MEAS3_TINT_SHIFT	3
#define MEAS3_AVER_MASK	0x07
#define MEAS3_AVER_SHIFT	0

#define MEAS3_CONFIGURATION_2_REGISTER	0x32
#define MEAS3_SINC3_SEL_MASK	0x80
#define MEAS3_SINC3_SEL_SHIFT	7
#define MEAS3_FILT_SEL_MASK	0x40
#define MEAS3_FILT_SEL_SHIFT	6
#define MEAS3_LED_RGE_MASK	0x30
#define MEAS3_LED_RGE_SHIFT	4
#define MEAS3_PPG2_ADC_RGE_MASK	0x0C
#define MEAS3_PPG2_ADC_RGE_SHIFT	2
#define MEAS3_PPG1_ADC_RGE_MASK	0x03
#define MEAS3_PPG1_ADC_RGE_SHIFT	0

#define MEAS3_CONFIGURATION_3_REGISTER	0x33
#define MEAS3_PD_SETLNG_MASK	0xC0
#define MEAS3_PD_SETLNG_SHIFT	6
#define MEAS3_LED_SETLNG_MASK	0x30
#define MEAS3_LED_SETLNG_SHIFT	4
#define MEAS3_PPG2_DACOFF_MASK	0x0C
#define MEAS3_PPG2_DACOFF_SHIFT	2
#define MEAS3_PPG1_DACOFF_MASK	0x03
#define MEAS3_PPG1_DACOFF_SHIFT	0

#define MEAS3_CONFIGURATION_4_REGISTER	0x34
#define MEAS3_BUFCHAN_MASK	0x40
#define MEAS3_BUFCHAN_SHIFT	6
#define MEAS3_PPG_GAIN_MASK	0x30
#define MEAS3_PPG_GAIN_SHIFT	4
#define MEAS3_PPG2_PDSEL_MASK	0x0C
#define MEAS3_PPG2_PDSEL_SHIFT	2
#define MEAS3_PPG1_PDSEL_MASK	0x03
#define MEAS3_PPG1_PDSEL_SHIFT	0

#define MEAS3_LEDA_CURRENT_REGISTER	0x35
#define MEAS3_DRVA_PA_MASK	0xFF
#define MEAS3_DRVA_PA_SHIFT	0

#define MEAS3_LEDB_CURRENT_REGISTER	0x36
#define MEAS3_DRVB_PA_MASK	0xFF
#define MEAS3_DRVB_PA_SHIFT	0

// Section - PPG MEAS4 Setup
#define MEAS4_SELECTS_REGISTER	0x38
#define MEAS4_AMB_MASK	0x40
#define MEAS4_AMB_SHIFT	6
#define MEAS4_DRVB_MASK	0x38
#define MEAS4_DRVB_SHIFT	3
#define MEAS4_DRVA_MASK	0x07
#define MEAS4_DRVA_SHIFT	0

#define MEAS4_CONFIGURATION_1_REGISTER	0x39
#define MEAS4_TINT_MASK	0x18
#define MEAS4_TINT_SHIFT	3
#define MEAS4_AVER_MASK	0x07
#define MEAS4_AVER_SHIFT	0

#define MEAS4_CONFIGURATION_2_REGISTER	0x3A
#define MEAS4_SINC3_SEL_MASK	0x80
#define MEAS4_SINC3_SEL_SHIFT	7
#define MEAS4_FILT_SEL_MASK	0x40
#define MEAS4_FILT_SEL_SHIFT	6
#define MEAS4_LED_RGE_MASK	0x30
#define MEAS4_LED_RGE_SHIFT	4
#define MEAS4_PPG2_ADC_RGE_MASK	0x0C
#define MEAS4_PPG2_ADC_RGE_SHIFT	2
#define MEAS4_PPG1_ADC_RGE_MASK	0x03
#define MEAS4_PPG1_ADC_RGE_SHIFT	0

#define MEAS4_CONFIGURATION_3_REGISTER	0x3B
#define MEAS4_PD_SETLNG_MASK	0xC0
#define MEAS4_PD_SETLNG_SHIFT	6
#define MEAS4_LED_SETLNG_MASK	0x30
#define MEAS4_LED_SETLNG_SHIFT	4
#define MEAS4_PPG2_DACOFF_MASK	0x0C
#define MEAS4_PPG2_DACOFF_SHIFT	2
#define MEAS4_PPG1_DACOFF_MASK	0x03
#define MEAS4_PPG1_DACOFF_SHIFT	0

#define MEAS4_CONFIGURATION_4_REGISTER	0x3C
#define MEAS4_BUFCHAN_MASK	0x40
#define MEAS4_BUFCHAN_SHIFT	6
#define MEAS4_PPG_GAIN_MASK	0x30
#define MEAS4_PPG_GAIN_SHIFT	4
#define MEAS4_PPG2_PDSEL_MASK	0x0C
#define MEAS4_PPG2_PDSEL_SHIFT	2
#define MEAS4_PPG1_PDSEL_MASK	0x03
#define MEAS4_PPG1_PDSEL_SHIFT	0

#define MEAS4_LEDA_CURRENT_REGISTER	0x3D
#define MEAS4_DRVA_PA_MASK	0xFF
#define MEAS4_DRVA_PA_SHIFT	0

#define MEAS4_LEDB_CURRENT_REGISTER	0x3E
#define MEAS4_DRVB_PA_MASK	0xFF
#define MEAS4_DRVB_PA_SHIFT	0

// Section - PPG MEAS5 Setup
#define MEAS5_SELECTS_REGISTER	0x40
#define MEAS5_AMB_MASK	0x40
#define MEAS5_AMB_SHIFT	6
#define MEAS5_DRVB_MASK	0x38
#define MEAS5_DRVB_SHIFT	3
#define MEAS5_DRVA_MASK	0x07
#define MEAS5_DRVA_SHIFT	0

#define MEAS5_CONFIGURATION_1_REGISTER	0x41
#define MEAS5_TINT_MASK	0x18
#define MEAS5_TINT_SHIFT	3
#define MEAS5_AVER_MASK	0x07
#define MEAS5_AVER_SHIFT	0

#define MEAS5_CONFIGURATION_2_REGISTER	0x42
#define MEAS5_SINC3_SEL_MASK	0x80
#define MEAS5_SINC3_SEL_SHIFT	7
#define MEAS5_FILT_SEL_MASK	0x40
#define MEAS5_FILT_SEL_SHIFT	6
#define MEAS5_LED_RGE_MASK	0x30
#define MEAS5_LED_RGE_SHIFT	4
#define MEAS5_PPG2_ADC_RGE_MASK	0x0C
#define MEAS5_PPG2_ADC_RGE_SHIFT	2
#define MEAS5_PPG1_ADC_RGE_MASK	0x03
#define MEAS5_PPG1_ADC_RGE_SHIFT	0

#define MEAS5_CONFIGURATION_3_REGISTER	0x43
#define MEAS5_PD_SETLNG_MASK	0xC0
#define MEAS5_PD_SETLNG_SHIFT	6
#define MEAS5_LED_SETLNG_MASK	0x30
#define MEAS5_LED_SETLNG_SHIFT	4
#define MEAS5_PPG2_DACOFF_MASK	0x0C
#define MEAS5_PPG2_DACOFF_SHIFT	2
#define MEAS5_PPG1_DACOFF_MASK	0x03
#define MEAS5_PPG1_DACOFF_SHIFT	0

#define MEAS5_CONFIGURATION_4_REGISTER	0x44
#define MEAS5_BUFCHAN_MASK	0x40
#define MEAS5_BUFCHAN_SHIFT	6
#define MEAS5_PPG_GAIN_MASK	0x30
#define MEAS5_PPG_GAIN_SHIFT	4
#define MEAS5_PPG2_PDSEL_MASK	0x0C
#define MEAS5_PPG2_PDSEL_SHIFT	2
#define MEAS5_PPG1_PDSEL_MASK	0x03
#define MEAS5_PPG1_PDSEL_SHIFT	0

#define MEAS5_LEDA_CURRENT_REGISTER	0x45
#define MEAS5_DRVA_PA_MASK	0xFF
#define MEAS5_DRVA_PA_SHIFT	0

#define MEAS5_LEDB_CURRENT_REGISTER	0x46
#define MEAS5_DRVB_PA_MASK	0xFF
#define MEAS5_DRVB_PA_SHIFT	0

// Section - PPG MEAS6 Setup
#define MEAS6_SELECTS_REGISTER	0x48
#define MEAS6_AMB_MASK	0x40
#define MEAS6_AMB_SHIFT	6
#define MEAS6_DRVB_MASK	0x38
#define MEAS6_DRVB_SHIFT	3
#define MEAS6_DRVA_MASK	0x07
#define MEAS6_DRVA_SHIFT	0

#define MEAS6_CONFIGURATION_1_REGISTER	0x49
#define MEAS6_TINT_MASK	0x18
#define MEAS6_TINT_SHIFT	3
#define MEAS6_AVER_MASK	0x07
#define MEAS6_AVER_SHIFT	0

#define MEAS6_CONFIGURATION_2_REGISTER	0x4A
#define MEAS6_SINC3_SEL_MASK	0x80
#define MEAS6_SINC3_SEL_SHIFT	7
#define MEAS6_FILT_SEL_MASK	0x40
#define MEAS6_FILT_SEL_SHIFT	6
#define MEAS6_LED_RGE_MASK	0x30
#define MEAS6_LED_RGE_SHIFT	4
#define MEAS6_PPG2_ADC_RGE_MASK	0x0C
#define MEAS6_PPG2_ADC_RGE_SHIFT	2
#define MEAS6_PPG1_ADC_RGE_MASK	0x03
#define MEAS6_PPG1_ADC_RGE_SHIFT	0

#define MEAS6_CONFIGURATION_3_REGISTER	0x4B
#define MEAS6_PD_SETLNG_MASK	0xC0
#define MEAS6_PD_SETLNG_SHIFT	6
#define MEAS6_LED_SETLNG_MASK	0x30
#define MEAS6_LED_SETLNG_SHIFT	4
#define MEAS6_PPG2_DACOFF_MASK	0x0C
#define MEAS6_PPG2_DACOFF_SHIFT	2
#define MEAS6_PPG1_DACOFF_MASK	0x03
#define MEAS6_PPG1_DACOFF_SHIFT	0

#define MEAS6_CONFIGURATION_4_REGISTER	0x4C
#define MEAS6_BUFCHAN_MASK	0x40
#define MEAS6_BUFCHAN_SHIFT	6
#define MEAS6_PPG_GAIN_MASK	0x30
#define MEAS6_PPG_GAIN_SHIFT	4
#define MEAS6_PPG2_PDSEL_MASK	0x0C
#define MEAS6_PPG2_PDSEL_SHIFT	2
#define MEAS6_PPG1_PDSEL_MASK	0x03
#define MEAS6_PPG1_PDSEL_SHIFT	0

#define MEAS6_LEDA_CURRENT_REGISTER	0x4D
#define MEAS6_DRVA_PA_MASK	0xFF
#define MEAS6_DRVA_PA_SHIFT	0

#define MEAS6_LEDB_CURRENT_REGISTER	0x4E
#define MEAS6_DRVB_PA_MASK	0xFF
#define MEAS6_DRVB_PA_SHIFT	0

// Section - PPG MEAS7 Setup
#define MEAS7_SELECTS_REGISTER	0x50
#define MEAS7_AMB_MASK	0x40
#define MEAS7_AMB_SHIFT	6
#define MEAS7_DRVB_MASK	0x38
#define MEAS7_DRVB_SHIFT	3
#define MEAS7_DRVA_MASK	0x07
#define MEAS7_DRVA_SHIFT	0

#define MEAS7_CONFIGURATION_1_REGISTER	0x51
#define MEAS7_TINT_MASK	0x18
#define MEAS7_TINT_SHIFT	3
#define MEAS7_AVER_MASK	0x07
#define MEAS7_AVER_SHIFT	0

#define MEAS7_CONFIGURATION_2_REGISTER	0x52
#define MEAS7_SINC3_SEL_MASK	0x80
#define MEAS7_SINC3_SEL_SHIFT	7
#define MEAS7_FILT_SEL_MASK	0x40
#define MEAS7_FILT_SEL_SHIFT	6
#define MEAS7_LED_RGE_MASK	0x30
#define MEAS7_LED_RGE_SHIFT	4
#define MEAS7_PPG2_ADC_RGE_MASK	0x0C
#define MEAS7_PPG2_ADC_RGE_SHIFT	2
#define MEAS7_PPG1_ADC_RGE_MASK	0x03
#define MEAS7_PPG1_ADC_RGE_SHIFT	0

#define MEAS7_CONFIGURATION_3_REGISTER	0x53
#define MEAS7_PD_SETLNG_MASK	0xC0
#define MEAS7_PD_SETLNG_SHIFT	6
#define MEAS7_LED_SETLNG_MASK	0x30
#define MEAS7_LED_SETLNG_SHIFT	4
#define MEAS7_PPG2_DACOFF_MASK	0x0C
#define MEAS7_PPG2_DACOFF_SHIFT	2
#define MEAS7_PPG1_DACOFF_MASK	0x03
#define MEAS7_PPG1_DACOFF_SHIFT	0

#define MEAS7_CONFIGURATION_4_REGISTER	0x54
#define MEAS7_BUFCHAN_MASK	0x40
#define MEAS7_BUFCHAN_SHIFT	6
#define MEAS7_PPG_GAIN_MASK	0x30
#define MEAS7_PPG_GAIN_SHIFT	4
#define MEAS7_PPG2_PDSEL_MASK	0x0C
#define MEAS7_PPG2_PDSEL_SHIFT	2
#define MEAS7_PPG1_PDSEL_MASK	0x03
#define MEAS7_PPG1_PDSEL_SHIFT	0

#define MEAS7_LEDA_CURRENT_REGISTER	0x55
#define MEAS7_DRVA_PA_MASK	0xFF
#define MEAS7_DRVA_PA_SHIFT	0

#define MEAS7_LEDB_CURRENT_REGISTER	0x56
#define MEAS7_DRVB_PA_MASK	0xFF
#define MEAS7_DRVB_PA_SHIFT	0

// Section - PPG MEAS8 Setup
#define MEAS8_SELECTS_REGISTER	0x58
#define MEAS8_AMB_MASK	0x40
#define MEAS8_AMB_SHIFT	6
#define MEAS8_DRVB_MASK	0x38
#define MEAS8_DRVB_SHIFT	3
#define MEAS8_DRVA_MASK	0x07
#define MEAS8_DRVA_SHIFT	0

#define MEAS8_CONFIGURATION_1_REGISTER	0x59
#define MEAS8_TINT_MASK	0x18
#define MEAS8_TINT_SHIFT	3
#define MEAS8_AVER_MASK	0x07
#define MEAS8_AVER_SHIFT	0

#define MEAS8_CONFIGURATION_2_REGISTER	0x5A
#define MEAS8_SINC3_SEL_MASK	0x80
#define MEAS8_SINC3_SEL_SHIFT	7
#define MEAS8_FILT_SEL_MASK	0x40
#define MEAS8_FILT_SEL_SHIFT	6
#define MEAS8_LED_RGE_MASK	0x30
#define MEAS8_LED_RGE_SHIFT	4
#define MEAS8_PPG2_ADC_RGE_MASK	0x0C
#define MEAS8_PPG2_ADC_RGE_SHIFT	2
#define MEAS8_PPG1_ADC_RGE_MASK	0x03
#define MEAS8_PPG1_ADC_RGE_SHIFT	0

#define MEAS8_CONFIGURATION_3_REGISTER	0x5B
#define MEAS8_PD_SETLNG_MASK	0xC0
#define MEAS8_PD_SETLNG_SHIFT	6
#define MEAS8_LED_SETLNG_MASK	0x30
#define MEAS8_LED_SETLNG_SHIFT	4
#define MEAS8_PPG2_DACOFF_MASK	0x0C
#define MEAS8_PPG2_DACOFF_SHIFT	2
#define MEAS8_PPG1_DACOFF_MASK	0x03
#define MEAS8_PPG1_DACOFF_SHIFT	0

#define MEAS8_CONFIGURATION_4_REGISTER	0x5C
#define MEAS8_BUFCHAN_MASK	0x40
#define MEAS8_BUFCHAN_SHIFT	6
#define MEAS8_PPG_GAIN_MASK	0x30
#define MEAS8_PPG_GAIN_SHIFT	4
#define MEAS8_PPG2_PDSEL_MASK	0x0C
#define MEAS8_PPG2_PDSEL_SHIFT	2
#define MEAS8_PPG1_PDSEL_MASK	0x03
#define MEAS8_PPG1_PDSEL_SHIFT	0

#define MEAS8_LEDA_CURRENT_REGISTER	0x5D
#define MEAS8_DRVA_PA_MASK	0xFF
#define MEAS8_DRVA_PA_SHIFT	0

#define MEAS8_LEDB_CURRENT_REGISTER	0x5E
#define MEAS8_DRVB_PA_MASK	0xFF
#define MEAS8_DRVB_PA_SHIFT	0

// Section - PPG MEAS9 Setup
#define MEAS9_SELECTS_REGISTER	0x60
#define MEAS9_AMB_MASK	0x40
#define MEAS9_AMB_SHIFT	6
#define MEAS9_DRVB_MASK	0x38
#define MEAS9_DRVB_SHIFT	3
#define MEAS9_DRVA_MASK	0x07
#define MEAS9_DRVA_SHIFT	0

#define MEAS9_CONFIGURATION_1_REGISTER	0x61
#define MEAS9_TINT_MASK	0x18
#define MEAS9_TINT_SHIFT	3
#define MEAS9_AVER_MASK	0x07
#define MEAS9_AVER_SHIFT	0

#define MEAS9_CONFIGURATION_2_REGISTER	0x62
#define MEAS9_SINC3_SEL_MASK	0x80
#define MEAS9_SINC3_SEL_SHIFT	7
#define MEAS9_FILT_SEL_MASK	0x40
#define MEAS9_FILT_SEL_SHIFT	6
#define MEAS9_LED_RGE_MASK	0x30
#define MEAS9_LED_RGE_SHIFT	4
#define MEAS9_PPG2_ADC_RGE_MASK	0x0C
#define MEAS9_PPG2_ADC_RGE_SHIFT	2
#define MEAS9_PPG1_ADC_RGE_MASK	0x03
#define MEAS9_PPG1_ADC_RGE_SHIFT	0

#define MEAS9_CONFIGURATION_3_REGISTER	0x63
#define MEAS9_PD_SETLNG_MASK	0xC0
#define MEAS9_PD_SETLNG_SHIFT	6
#define MEAS9_LED_SETLNG_MASK	0x30
#define MEAS9_LED_SETLNG_SHIFT	4
#define MEAS9_PPG2_DACOFF_MASK	0x0C
#define MEAS9_PPG2_DACOFF_SHIFT	2
#define MEAS9_PPG1_DACOFF_MASK	0x03
#define MEAS9_PPG1_DACOFF_SHIFT	0

#define MEAS9_CONFIGURATION_4_REGISTER	0x64
#define MEAS9_BUFCHAN_MASK	0x40
#define MEAS9_BUFCHAN_SHIFT	6
#define MEAS9_PPG_GAIN_MASK	0x30
#define MEAS9_PPG_GAIN_SHIFT	4
#define MEAS9_PPG2_PDSEL_MASK	0x0C
#define MEAS9_PPG2_PDSEL_SHIFT	2
#define MEAS9_PPG1_PDSEL_MASK	0x03
#define MEAS9_PPG1_PDSEL_SHIFT	0

#define MEAS9_LEDA_CURRENT_REGISTER	0x65
#define MEAS9_DRVA_PA_MASK	0xFF
#define MEAS9_DRVA_PA_SHIFT	0

#define MEAS9_LEDB_CURRENT_REGISTER	0x66
#define MEAS9_DRVB_PA_MASK	0xFF
#define MEAS9_DRVB_PA_SHIFT	0

// Section - PPG Threshold Interrupts
#define THRESHOLD_MEAS_SEL_REGISTER	0x70
#define THRESH2_MEAS_SEL_MASK	0xF0
#define THRESH2_MEAS_SEL_SHIFT	4
#define THRESH1_MEAS_SEL_MASK	0x0F
#define THRESH1_MEAS_SEL_SHIFT	0

#define THRESHOLD_HYST_REGISTER	0x71
#define THRESH2_PPG_SEL_MASK	0x80
#define THRESH2_PPG_SEL_SHIFT	7
#define THRESH1_PPG_SEL_MASK	0x40
#define THRESH1_PPG_SEL_SHIFT	6
#define TIME_HYST_MASK	0x18
#define TIME_HYST_SHIFT	3
#define LEVEL_HYST_MASK	0x07
#define LEVEL_HYST_SHIFT	0

#define PPG_HI_THRESHOLD1_REGISTER	0x72
#define THRESHOLD1_UPPER_MASK	0xFF
#define THRESHOLD1_UPPER_SHIFT	0

#define PPG_LO_THRESHOLD1_REGISTER	0x73
#define THRESHOLD1_LOWER_MASK	0xFF
#define THRESHOLD1_LOWER_SHIFT	0

#define PPG_HI_THRESHOLD2_REGISTER	0x74
#define THRESHOLD2_UPPER_MASK	0xFF
#define THRESHOLD2_UPPER_SHIFT	0

#define PPG_LO_THRESHOLD2_REGISTER	0x75
#define THRESHOLD2_LOWER_MASK	0xFF
#define THRESHOLD2_LOWER_SHIFT	0

// Section - Interrupt Enables
#define INTERRUPT_1_ENABLE_1_REGISTER	0x80
#define A_FULL_EN1_MASK	0x80
#define A_FULL_EN1_SHIFT	7
#define FRAME_RDY_EN1_MASK	0x40
#define FRAME_RDY_EN1_SHIFT	6
#define FIFO_DATA_RDY_EN1_MASK	0x20
#define FIFO_DATA_RDY_EN1_SHIFT	5
#define ALC_OVF_EN1_MASK	0x10
#define ALC_OVF_EN1_SHIFT	4
#define EXP_OVF_EN1_MASK	0x08
#define EXP_OVF_EN1_SHIFT	3
#define THRESH2_HILO_EN1_MASK	0x04
#define THRESH2_HILO_EN1_SHIFT	2
#define THRESH1_HILO_EN1_MASK	0x02
#define THRESH1_HILO_EN1_SHIFT	1
#define LED_TX_EN1_MASK	0x01
#define LED_TX_EN1_SHIFT	0

#define INTERRUPT_1_ENABLE_2_REGISTER	0x81
#define TIMING_SYS_RESET_EN1_MASK	0x80
#define TIMING_SYS_RESET_EN1_SHIFT	7
#define VDD_OOR_EN1_MASK	0x40
#define VDD_OOR_EN1_SHIFT	6
#define INVALID_CFG_EN1_MASK	0x04
#define INVALID_CFG_EN1_SHIFT	2

#define INTERRUPT_1_ENABLE_3_REGISTER	0x82
#define LED6_COMPB_EN1_MASK	0x20
#define LED6_COMPB_EN1_SHIFT	5
#define LED5_COMPB_EN1_MASK	0x10
#define LED5_COMPB_EN1_SHIFT	4
#define LED4_COMPB_EN1_MASK	0x08
#define LED4_COMPB_EN1_SHIFT	3
#define LED3_COMPB_EN1_MASK	0x04
#define LED3_COMPB_EN1_SHIFT	2
#define LED2_COMPB_EN1_MASK	0x02
#define LED2_COMPB_EN1_SHIFT	1
#define LED1_COMPB_EN1_MASK	0x01
#define LED1_COMPB_EN1_SHIFT	0

#define INTERRUPT_1_ENABLE_4_REGISTER	0x83
#define PD4_SHORT_EN1_MASK	0x08
#define PD4_SHORT_EN1_SHIFT	3
#define PD3_SHORT_EN1_MASK	0x04
#define PD3_SHORT_EN1_SHIFT	2
#define PD2_SHORT_EN1_MASK	0x02
#define PD2_SHORT_EN1_SHIFT	1
#define PD1_SHORT_EN1_MASK	0x01
#define PD1_SHORT_EN1_SHIFT	0

#define INTERRUPT_1_ENABLE_5_REGISTER	0x84
#define ECG_FAST_REC_EN1_MASK	0x80
#define ECG_FAST_REC_EN1_SHIFT	7
#define RLD_OOR_EN1_MASK	0x08
#define RLD_OOR_EN1_SHIFT	3
#define PLL_UNLOCK_EN1_MASK	0x04
#define PLL_UNLOCK_EN1_SHIFT	2
#define PLL_LOCK_EN1_MASK	0x02
#define PLL_LOCK_EN1_SHIFT	1
#define SAMP_SYNC_EN1_MASK	0x01
#define SAMP_SYNC_EN1_SHIFT	0

#define INTERRUPT_1_ENABLE_6_REGISTER	0x85
#define LON_EN1_MASK	0x80
#define LON_EN1_SHIFT	7
#define AC_LOFF_EN1_MASK	0x20
#define AC_LOFF_EN1_SHIFT	5
#define DC_LOFF_PH_EN1_MASK	0x08
#define DC_LOFF_PH_EN1_SHIFT	3
#define DC_LOFF_PL_EN1_MASK	0x04
#define DC_LOFF_PL_EN1_SHIFT	2
#define DC_LOFF_NH_EN1_MASK	0x02
#define DC_LOFF_NH_EN1_SHIFT	1
#define DC_LOFF_NL_EN1_MASK	0x01
#define DC_LOFF_NL_EN1_SHIFT	0

#define INTERRUPT_2_ENABLE_1_REGISTER	0x86
#define A_FULL_EN2_MASK	0x80
#define A_FULL_EN2_SHIFT	7
#define FRAME_RDY_EN2_MASK	0x40
#define FRAME_RDY_EN2_SHIFT	6
#define FIFO_DATA_RDY_EN2_MASK	0x20
#define FIFO_DATA_RDY_EN2_SHIFT	5
#define ALC_OVF_EN2_MASK	0x10
#define ALC_OVF_EN2_SHIFT	4
#define EXP_OVF_EN2_MASK	0x08
#define EXP_OVF_EN2_SHIFT	3
#define THRESH2_HILO_EN2_MASK	0x04
#define THRESH2_HILO_EN2_SHIFT	2
#define THRESH1_HILO_EN2_MASK	0x02
#define THRESH1_HILO_EN2_SHIFT	1
#define LED_TX_EN2_MASK	0x01
#define LED_TX_EN2_SHIFT	0

#define INTERRUPT_2_ENABLE_2_REGISTER	0x87
#define TIMING_SYS_RESET_EN2_MASK	0x80
#define TIMING_SYS_RESET_EN2_SHIFT	7
#define VDD_OOR_EN2_MASK	0x40
#define VDD_OOR_EN2_SHIFT	6
#define INVALID_CFG_EN2_MASK	0x04
#define INVALID_CFG_EN2_SHIFT	2

#define INTERRUPT_2_ENABLE_3_REGISTER	0x88
#define LED6_COMPB_EN2_MASK	0x20
#define LED6_COMPB_EN2_SHIFT	5
#define LED5_COMPB_EN2_MASK	0x10
#define LED5_COMPB_EN2_SHIFT	4
#define LED4_COMPB_EN2_MASK	0x08
#define LED4_COMPB_EN2_SHIFT	3
#define LED3_COMPB_EN2_MASK	0x04
#define LED3_COMPB_EN2_SHIFT	2
#define LED2_COMPB_EN2_MASK	0x02
#define LED2_COMPB_EN2_SHIFT	1
#define LED1_COMPB_EN2_MASK	0x01
#define LED1_COMPB_EN2_SHIFT	0

#define INTERRUPT_2_ENABLE_4_REGISTER	0x89
#define PD4_SHORT_EN2_MASK	0x08
#define PD4_SHORT_EN2_SHIFT	3
#define PD3_SHORT_EN2_MASK	0x04
#define PD3_SHORT_EN2_SHIFT	2
#define PD2_SHORT_EN2_MASK	0x02
#define PD2_SHORT_EN2_SHIFT	1
#define PD1_SHORT_EN2_MASK	0x01
#define PD1_SHORT_EN2_SHIFT	0

#define INTERRUPT_2_ENABLE_5_REGISTER	0x8A
#define ECG_FAST_REC_EN2_MASK	0x80
#define ECG_FAST_REC_EN2_SHIFT	7
#define RLD_OOR_EN2_MASK	0x08
#define RLD_OOR_EN2_SHIFT	3
#define PLL_UNLOCK_EN2_MASK	0x04
#define PLL_UNLOCK_EN2_SHIFT	2
#define PLL_LOCK_EN2_MASK	0x02
#define PLL_LOCK_EN2_SHIFT	1
#define SAMP_SYNC_EN2_MASK	0x01
#define SAMP_SYNC_EN2_SHIFT	0

#define INTERRUPT_2_ENABLE_6_REGISTER	0x8B
#define LON_EN2_MASK	0x80
#define LON_EN2_SHIFT	7
#define AC_LOFF_EN2_MASK	0x20
#define AC_LOFF_EN2_SHIFT	5
#define DC_LOFF_PH_EN2_MASK	0x08
#define DC_LOFF_PH_EN2_SHIFT	3
#define DC_LOFF_PL_EN2_MASK	0x04
#define DC_LOFF_PL_EN2_SHIFT	2
#define DC_LOFF_NH_EN2_MASK	0x02
#define DC_LOFF_NH_EN2_SHIFT	1
#define DC_LOFF_NL_EN2_MASK	0x01
#define DC_LOFF_NL_EN2_SHIFT	0

// Section - ECG Setup
#define ECG_CONFIGURATION_1_REGISTER	0x90
#define ECG_EN_MASK	0x80
#define ECG_EN_SHIFT	7
#define ECG_DEC_RATE_MASK	0x07
#define ECG_DEC_RATE_SHIFT	0

#define ECG_CONFIGURATION_2_REGISTER	0x91
#define ECG_IPOL_MASK	0x80
#define ECG_IPOL_SHIFT	7
#define ECG_PGA_GAIN_MASK	0x70
#define ECG_PGA_GAIN_SHIFT	4
#define ECG_INA_GAIN_MASK	0x03
#define ECG_INA_GAIN_SHIFT	0

#define ECG_CONFIGURATION_3_REGISTER	0x92
#define EN_ECG_FAST_REC_MASK	0xC0
#define EN_ECG_FAST_REC_SHIFT	6
#define ECG_FAST_REC_THRESHOLD_MASK	0x3F
#define ECG_FAST_REC_THRESHOLD_SHIFT	0

// Section - ECG Lead Detect
#define LEAD_DETECT_CONFIGURATION_1_REGISTER	0x93
#define EN_LON_DET_MASK	0x80
#define EN_LON_DET_SHIFT	7
#define EN_LOFF_DET_MASK	0x60
#define EN_LOFF_DET_SHIFT	5
#define DAC_STIM_MODE_MASK	0x10
#define DAC_STIM_MODE_SHIFT	4
#define LOFF_SETTLE_MASK	0x0F
#define LOFF_SETTLE_SHIFT	0

#define LEAD_DETECT_CONFIGURATION_2_REGISTER	0x94
#define DC_LOFF_RAPID_MASK	0x80
#define DC_LOFF_RAPID_SHIFT	7
#define HI_CM_RES_EN_MASK	0x40
#define HI_CM_RES_EN_SHIFT	6
#define LOFF_CG_MODE_MASK	0x30
#define LOFF_CG_MODE_SHIFT	4
#define LOFF_IMAG_MASK	0x0F
#define LOFF_IMAG_SHIFT	0

#define AC_LEAD_DETECT_WAVEFORM_REGISTER	0x95
#define AC_LOFF_IWAVE_MASK	0x80
#define AC_LOFF_IWAVE_SHIFT	7
#define AC_LOFF_FREQ_DIV_MASK	0x7F
#define AC_LOFF_FREQ_DIV_SHIFT	0

#define DC_LEAD_DETECT_DAC_CODE_REGISTER	0x96
#define AC_LOFF_CONV_MASK	0xC0
#define AC_LOFF_CONV_SHIFT	6
#define DC_LOFF_DAC_CODE_MASK	0x3F
#define DC_LOFF_DAC_CODE_SHIFT	0

#define DC_LEAD_OFF_THRESHOLD_REGISTER	0x97
#define LOFF_CG_LPF_MASK	0xF0
#define LOFF_CG_LPF_SHIFT	4
#define DC_LOFF_THRESH_MASK	0x0F
#define DC_LOFF_THRESH_SHIFT	0

#define AC_LEAD_OFF_THRESHOLD_1_REGISTER	0x98
#define AC_LOFF_CMP_MASK	0xC0
#define AC_LOFF_CMP_SHIFT	6

#define AC_LEAD_OFF_THRESHOLD_2_REGISTER	0x99
#define AC_LOFF_THRESH_MASK	0xFF
#define AC_LOFF_THRESH_SHIFT	0

#define AC_LEAD_OFF_PGA_HPF_REGISTER	0x9A
#define AC_LOFF_UTIL_PGA_GAIN_MASK	0xC0
#define AC_LOFF_UTIL_PGA_GAIN_SHIFT	6
#define AC_LOFF_HPF_MASK	0x07
#define AC_LOFF_HPF_SHIFT	0

#define AC_LEAD_OFF_CALIBRATION_RES_REGISTER	0x9B
#define AC_LOFF_CAL_RES_VAR_MASK	0xFF
#define AC_LOFF_CAL_RES_VAR_SHIFT	0

// Section - ECG Lead Bias
#define LEAD_BIAS_CONFIGURATION_1_REGISTER	0x9E
#define RBIAS_VALUE_MASK	0x0C
#define RBIAS_VALUE_SHIFT	2
#define EN_RBIAS_P_MASK	0x02
#define EN_RBIAS_P_SHIFT	1
#define EN_RBIAS_N_MASK	0x01
#define EN_RBIAS_N_SHIFT	0

// Section - ECG Calibration
#define CAL_CONFIGURATION_1_REGISTER	0xA0
#define CAL_EN_MASK	0x80
#define CAL_EN_SHIFT	7
#define CAL_FREQ_MASK	0x70
#define CAL_FREQ_SHIFT	4
#define CAL_DUTY_MASK	0x08
#define CAL_DUTY_SHIFT	3
#define CAL_HIGH_MSB_MASK	0x07
#define CAL_HIGH_MSB_SHIFT	0

#define CAL_CONFIGURATION_2_REGISTER	0xA1
#define CAL_HIGH_LSB_MASK	0xFF
#define CAL_HIGH_LSB_SHIFT	0

#define CAL_CONFIGURATION_3_REGISTER	0xA2
#define OPEN_P_MASK	0x80
#define OPEN_P_SHIFT	7
#define OPEN_N_MASK	0x40
#define OPEN_N_SHIFT	6
#define CAL_MODE_MASK	0x20
#define CAL_MODE_SHIFT	5
#define CAL_MAG_MASK	0x10
#define CAL_MAG_SHIFT	4
#define CAL_P_SEL_MASK	0x0C
#define CAL_P_SEL_SHIFT	2
#define CAL_N_SEL_MASK	0x03
#define CAL_N_SEL_SHIFT	0

// Section - ECG RLD and CM Amps
#define RLD_CONFIGURATION_1_REGISTER	0xA8
#define RLD_EN_MASK	0x80
#define RLD_EN_SHIFT	7
#define RLD_MODE_MASK	0x40
#define RLD_MODE_SHIFT	6
#define RLD_OOR_RAPID_MASK	0x20
#define RLD_OOR_RAPID_SHIFT	5
#define EN_RLD_OOR_MASK	0x10
#define EN_RLD_OOR_SHIFT	4
#define ACTV_CM_P_MASK	0x08
#define ACTV_CM_P_SHIFT	3
#define ACTV_CM_N_MASK	0x04
#define ACTV_CM_N_SHIFT	2
#define RLD_GAIN_MASK	0x03
#define RLD_GAIN_SHIFT	0

#define RLD_CONFIGURATION_2_REGISTER	0xA9
#define RLD_EXT_RES_MASK	0x80
#define RLD_EXT_RES_SHIFT	7
#define SEL_VCM_IN_MASK	0x40
#define SEL_VCM_IN_SHIFT	6
#define RLD_BW_MASK	0x30
#define RLD_BW_SHIFT	4
#define BODY_BIAS_DAC_MASK	0x0F
#define BODY_BIAS_DAC_SHIFT	0

// Section - Utility ADC
#define UTILITY_ADC_CONFIGURATION_1_REGISTER	0xE0
#define UTILITY_ADC_START_MASK	0x80
#define UTILITY_ADC_START_SHIFT	7
#define UTILITY_ADC_MUX_MASK	0x1F
#define UTILITY_ADC_MUX_SHIFT	0

#define UTILITY_ADC_DATA_HIGH_REGISTER	0xE1
#define UTILITY_ADC_DATA_MSB_MASK	0x0F
#define UTILITY_ADC_DATA_MSB_SHIFT	0

#define UTILITY_ADC_DATA_LOW_REGISTER	0xE2
#define UTILITY_ADC_DATA_LSB_MASK	0xFF
#define UTILITY_ADC_DATA_LSB_SHIFT	0

// Section - Part ID
#define PART_ID_REGISTER	0xFF
#define PART_ID_MASK	0xFF
#define PART_ID_SHIFT	0


#define AFE_I2C_ADDRESS			0x66	/* 7-bit I2C address; datasheet includes the read/write bit */
#define AFE_FIFO_SIZE			256
#define NUM_BYTES_PER_SAMPLE	3
#define NUM_STATUS_REGS			6
#define EXTRABUFFER				10

#define NUM_FRAMES_PER_INT		1
#define NUM_MEAS_PER_FRAME		3	/* number of enabled measurments */
#define NUM_PPG_PER_MEAS		2	/* number of enabled PPG channels */
#define NUM_SAMPLES_PER_INT		(NUM_FRAMES_PER_INT*NUM_MEAS_PER_FRAME*NUM_PPG_PER_MEAS+EXTRABUFFER)	/* number of samples in FIFO that generates a FIFO_A_FULL interrupt */

typedef enum
{
	//Status:1~6
	REG_STATUS					= 0x00,
	//FIFO 
	REG_FIFO_WR_PTR 			= 0x08,
	REG_FIFO_RD_PTR 			= 0x09,
	REG_FIFO_COUNTER 			= 0x0A,
	REG_FIFO_DATA 				= 0x0C,
	REG_FIFO_CFG_1 				= 0x0D,
	REG_FIFO_CFG_2 				= 0x0E,
	//System Control
	REG_SYS_CFG_1 				= 0x10,
	REG_SYS_CFG_2 				= 0x11,
	REG_SYS_CFG_3 				= 0x12,
	REG_SYS_CFG_4 				= 0x13,
	REG_SYS_PD_BIAS 			= 0x14,
	REG_SYS_INT_FCFG 			= 0x15,
	REG_SYS_INT_OCFG 			= 0x16,
	REG_SYS_I2C_ADDRESS 		= 0x17,
	//PLL
	REG_PLL_CFG_1 				= 0x18,
	REG_PLL_CFG_2 				= 0x19,
	REG_PLL_CFG_3 				= 0x1A,
	//PPG Frame Rate Clock
	REG_PPG_FR_CLK_SEL 			= 0x1C,
	REG_PPG_FR_CLK_DIV_H 		= 0x1D,
	REG_PPG_FR_CLK_DIV_L 		= 0x1E,
	//PPG MEAS1 Setup
	REG_PPG_MEAS1_SEL 			= 0x20,
	REG_PPG_MEAS1_CFG_1 		= 0x21,
	REG_PPG_MEAS1_CFG_2 		= 0x22,
	REG_PPG_MEAS1_CFG_3 		= 0x23,
	REG_PPG_MEAS1_CFG_4 		= 0x24,
	REG_PPG_MEAS1_LEDA_CUR 		= 0x25,
	REG_PPG_MEAS1_LEDB_CUR 		= 0x26,
	//PPG MEAS2 Setup
	REG_PPG_MEAS2_SEL 			= 0x28,
	REG_PPG_MEAS2_CFG_1 		= 0x29,
	REG_PPG_MEAS2_CFG_2 		= 0x2A,
	REG_PPG_MEAS2_CFG_3 		= 0x2B,
	REG_PPG_MEAS2_CFG_4 		= 0x2C,
	REG_PPG_MEAS2_LEDA_CUR 		= 0x2D,
	REG_PPG_MEAS2_LEDB_CUR 		= 0x2E,
	//PPG MEAS3 Setup
	REG_PPG_MEAS3_SEL 			= 0x30,
	REG_PPG_MEAS3_CFG_1 		= 0x31,
	REG_PPG_MEAS3_CFG_2 		= 0x32,
	REG_PPG_MEAS3_CFG_3 		= 0x33,
	REG_PPG_MEAS3_CFG_4 		= 0x34,
	REG_PPG_MEAS3_LEDA_CUR 		= 0x35,
	REG_PPG_MEAS3_LEDB_CUR 		= 0x36,
	//PPG MEAS4 Setup
	REG_PPG_MEAS4_SEL 			= 0x38,
	REG_PPG_MEAS4_CFG_1 		= 0x39,
	REG_PPG_MEAS4_CFG_2 		= 0x3A,
	REG_PPG_MEAS4_CFG_3 		= 0x3B,
	REG_PPG_MEAS4_CFG_4 		= 0x3C,
	REG_PPG_MEAS4_LEDA_CUR 		= 0x3D,
	REG_PPG_MEAS4_LEDB_CUR 		= 0x3E,
	//PPG MEAS5 Setup
	REG_PPG_MEAS5_SEL 			= 0x40,
	REG_PPG_MEAS5_CFG_1 		= 0x41,
	REG_PPG_MEAS5_CFG_2 		= 0x42,
	REG_PPG_MEAS5_CFG_3 		= 0x43,
	REG_PPG_MEAS5_CFG_4 		= 0x44,
	REG_PPG_MEAS5_LEDA_CUR 		= 0x45,
	REG_PPG_MEAS5_LEDB_CUR 		= 0x46,
	//PPG MEAS6 Setup
	REG_PPG_MEAS6_SEL 			= 0x48,
	REG_PPG_MEAS6_CFG_1 		= 0x49,
	REG_PPG_MEAS6_CFG_2 		= 0x4A,
	REG_PPG_MEAS6_CFG_3 		= 0x4B,
	REG_PPG_MEAS6_CFG_4 		= 0x4C,
	REG_PPG_MEAS6_LEDA_CUR 		= 0x4D,
	REG_PPG_MEAS6_LEDB_CUR 		= 0x4E,
	//PPG MEAS7 Setup
	REG_PPG_MEAS7_SEL 			= 0x50,
	REG_PPG_MEAS7_CFG_1 		= 0x51,
	REG_PPG_MEAS7_CFG_2 		= 0x52,
	REG_PPG_MEAS7_CFG_3 		= 0x53,
	REG_PPG_MEAS7_CFG_4 		= 0x54,
	REG_PPG_MEAS7_LEDA_CUR 		= 0x55,
	REG_PPG_MEAS7_LEDB_CUR 		= 0x56,	
	//PPG MEAS8 Setup
	REG_PPG_MEAS8_SEL 			= 0x58,
	REG_PPG_MEAS8_CFG_1 		= 0x59,
	REG_PPG_MEAS8_CFG_2 		= 0x5A,
	REG_PPG_MEAS8_CFG_3 		= 0x5B,
	REG_PPG_MEAS8_CFG_4 		= 0x5C,
	REG_PPG_MEAS8_LEDA_CUR 		= 0x5D,
	REG_PPG_MEAS8_LEDB_CUR 		= 0x5E,	
	//PPG MEAS9 Setup
	REG_PPG_MEAS9_SEL 			= 0x60,
	REG_PPG_MEAS9_CFG_1 		= 0x61,
	REG_PPG_MEAS9_CFG_2 		= 0x62,
	REG_PPG_MEAS9_CFG_3 		= 0x63,
	REG_PPG_MEAS9_CFG_4 		= 0x64,
	REG_PPG_MEAS9_LEDA_CUR 		= 0x65,
	REG_PPG_MEAS9_LEDB_CUR 		= 0x66,
	//PPG Threshold Interrupts
	REG_PPG_THRESHOLD_MEAS_SEL 	= 0x70,
	REG_PPG_THRESHOLD_HYST 		= 0x71,
	REG_PPG_THRESHOLD_1_H 		= 0x72,
	REG_PPG_THRESHOLD_1_L 		= 0x73,
	REG_PPG_THRESHOLD_2_H 		= 0x74,
	REG_PPG_THRESHOLD_2_L 		= 0x75,
	//Interrupt Enables 
	REG_INTERRUPT_1_ENABLE_1 	= 0x80,
	REG_INTERRUPT_1_ENABLE_2 	= 0x81,
	REG_INTERRUPT_1_ENABLE_3 	= 0x82,
	REG_INTERRUPT_1_ENABLE_4 	= 0x83,
	REG_INTERRUPT_1_ENABLE_5 	= 0x84,
	REG_INTERRUPT_1_ENABLE_6 	= 0x85,
	REG_INTERRUPT_2_ENABLE_1 	= 0x86,
	REG_INTERRUPT_2_ENABLE_2 	= 0x87,
	REG_INTERRUPT_2_ENABLE_3 	= 0x88,
	REG_INTERRUPT_2_ENABLE_4 	= 0x89,
	REG_INTERRUPT_2_ENABLE_5 	= 0x8A,
	REG_INTERRUPT_2_ENABLE_6 	= 0x8B,
	//ECG Setup
	REG_ECG_CFG_1 				= 0x90,
	REG_ECG_CFG_2 				= 0x91,
	REG_ECG_CFG_3 				= 0x92,
	//ECG Lead Detect 
	REG_ECG_LD_CFG_1 			= 0x93,
	REG_ECG_LD_CFG_2 			= 0x94,
	REG_ECG_AC_LD_WAVE 			= 0x95,
	REG_ECG_DC_LD_DAC_CODE 		= 0x96,
	REG_ECG_DC_LOFF_THRESHOLD 	= 0x97,
	REG_ECG_AC_LOFF_THRESHOLD_1 = 0x98,
	REG_ECG_AC_LOFF_THRESHOLD_2 = 0x99,
	REG_ECG_AC_LOFF_PGA_HPF 	= 0x9A,
	REG_ECG_AC_LOFF_CALIBRATION = 0x9B,
	//ECG Lead Bias
	REG_ECG_LD_BIAS_CFG 		= 0x9E,
	//ECG Calibration 
	REG_ECG_CAL_CFG_1 			= 0xA0,
	REG_ECG_CAL_CFG_2 			= 0xA1,
	REG_ECG_CAL_CFG_3 			= 0xA2,
	//ECG RLD and CM Amps 
	REG_ECG_RLD_CFG_1 			= 0xA8,
	REG_ECG_RLD_CFG_2 			= 0xA9,
	//Utility ADC
	REG_UTI_ADC_CFG 			= 0xE0,
	REG_UTI_ADC_DATA_H 			= 0xE1,
	REG_UTI_ADC_DATA_L 			= 0xE2,
	//Part ID 
	REG_PART_ID 				= 0xFF
}REGISTER_MAP;

typedef enum
{
	TAG_PPG_MAX = 0x0b,
	TAG_ECG = 0xc,
	TAG_TIME = 0xd,
	TAG_LOFFUTIL = 0xe,
	TAG_LOFF_I = 0,
	TAG_LOFF_Q = 1,
}TAG_TYPE;

typedef enum
{
	IX_LOFF_I = 0,
	IX_LOFF_Q,
	IX_ECG,
	IX_PPG,
	IX_TIME,
	NUM_ADC,
}IX_TYPE;

#endif/*__MAX86176_H__*/